### PR TITLE
Adding GEDI download option to remote data module

### PR DESCRIPTION
**Pull request by ayushprd**
## Description

This PR adds the option to download GEDI L1B, L2A and L2B data using the LP DAAC data pool.

 Not sure if it would be relevant but I have also added a script to retrieve the [Global Forest Canopy Height, 2019](https://glad.umd.edu/dataset/gedi) dataset on GEE which is based on GEDI data.

To test the PR the following settings configuration can be used:
For testing the datapool option
```
  <remotedata>
  <out_get_data>gedi</out_get_data>
  <source>datapool</source>
  <collection>GEDI02_B.002</collection>
  </remotedata>
  <run>
    <site>
      <id>772</id>
      <met.start>2019-01-01 00:00:00</met.start>
      <met.end>2019-03-30 00:00:00</met.end>
    </site>
    <inputs>
      <met>
        <id></id>
      </met>
    </inputs>
    <start.date>2019/01/01</start.date>
    <end.date>2019/03/30</end.date>
  </run>
```

For testing the GEE option
```
  <remotedata>
  <out_get_data>gedi</out_get_data>
  <source>gee</source>
  <collection>users/potapovpeter/GEDI_V27</collection>
  </remotedata>
  <run>
    <site>
      <id>772</id>
      <met.start>2019-12-01 00:00:00</met.start>
      <met.end>2019-12-31 00:00:00</met.end>
    </site>
    <inputs>
      <met>
        <id></id>
      </met>
    </inputs>
    <start.date>2019/01/01</start.date>
    <end.date>2019/12/31</end.date>
  </run>
```

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
I find the `<out_get_data>` and `<source>datapool</source>` syntax to be really confusing. What concept is the "out get data" tag trying to represent? Is there a better, more informative, name for this? 

Also, having a source named "datapool" is too uninformative/generic. Maybe change it to "LPDAAC" or "LPDAACdatapool" or something like that? 

More broadly, the PR needs more updates to the documentation. Maybe a table explaining what source, out_get_data, and collection options that are available? (if there are a lot of collections for a give source & out_get_data combo, the table might summarize the missions represented and give a link to the full detailed collection lists). 

A module that connects PEcAn to LPDAAC should provide us access to a lot more data than just GEDI, which is worth documenting even if the downstream tools to make use of over data aren't in place yet.

**Comment by mdietze** [comment]
@ayushprd just wanted to check on this PR since it seems close, and currently builds successfully, and the requested changes seem pretty minor.

**Comment by ayushprd** [comment]
Hi @mdietze sorry for the delay, I still need to make a couple of changes, would be ready by next Monday.

**Comment by istfer** [comment]
> Also, having a source named "datapool" is too uninformative/generic. Maybe change it to "LPDAAC" or "LPDAACdatapool" or something like that?

Agreed and now changed this to LPDAACdatapool

> I find the <out_get_data> and <source>datapool</source> syntax to be really confusing. What concept is the "out get data" tag trying to represent? Is there a better, more informative, name for this?More broadly, the PR needs more updates to the documentation. 

@ayushprd can correct me if I'm wrong, but there are two general steps in the remote data module (RpTools) `get_data` and `process_data`. `out_*` in this case is the prefix that specifies the requested output from the respective step., i.e. there are both `out_get_data` and `out_process_data` tags [as documented by Ayush](https://github.com/PecanProject/pecan/blob/develop/book_source/03_topical_pages/09_standalone_tools.Rmd#L217). As it is documented, I'm leaving it as is but I agree that it's maybe not the best wording. If you suggest something else I'm happy to make the change.

> A module that connects PEcAn to LPDAAC should provide us access to a lot more data than just GEDI, which is worth documenting even if the downstream tools to make use of over data aren't in place yet.

I'm not sure what it requires to download and process other datasets there but I'm seeing some GEDI specific steps in the `lpdaacdatapool2pecan` function. Probably it's possible to extend this functionality as Ayush implemented it. I added some docs regarding LP DAAC data source, hope it clarifies.

> Maybe a table explaining what source, out_get_data, and collection options that are available? (if there are a lot of collections for a give source & out_get_data combo, the table might summarize the missions represented and give a link to the full detailed collection lists).

I didn't add a table but updated the docs. Together with the existing documentation and the external links there, how does it look? Again Ayush can correct me if I'm wrong but there are currently 3 main `source`s in this module: GEE, AppEEARS and LP DAAC data server. From GEE you can download a couple of datasets (S-2, SMAP, Landsat8, GEDI Global Forest Canopy) for which documentation is up to-date, I think almost all AppEEARS products are accessible (and there is a link to the collection list), and from LP DAAC data server only the GEDI link is established. All in the documentation now.

I think I'm done with this round of revisions, it's ready for review again.

**Comment by ayushprd** [comment]
Apologies for not being able to get to this. Thanks a lot @istfer for making the changes. In the current state, the `lpdaacdatapool2pecan` function will be able to download the raw files of the other data products as well but it would stop after downloading (https://github.com/PecanProject/pecan/pull/2840/files#diff-5c863e17940b0c0a6a40cd57e9f0fb689836ff85a7e03f57e0124be764ceec30R146) and won't continue ahead with the workflow (adding to BETYdb, merging existing data, etc) as while working with the GEDI option I realized it requires further post-processing and I'm not sure how it is with other products on LPDAAC. The GEDI-specific processing is in a separate function so I think it should be possible to make this function work with other products in a similar way as per need.

**Review by mdietze — APPROVED** [review]

**Comment by mdietze** [comment]
Thanks @ayushprd and @istfer!

@serbinsh @DongchenZ @helge22a and Cherry, please make sure to look at these features since they should help with our NASA CMS project.

**Pull request merged**
