### PR TITLE
Updates & speed up to temporal downscaling code

### PR DESCRIPTION
**Pull request by crollinson**
Manually bringing in updates to the met ensemble / met downscaling code for PalEON.  This round greatly speeds up up the temporal downscaling process by reducing the amount of information being saved about each daily met model.  See commits here for more info: https://github.com/PalEON-Project/modeling_met_ensemble/commits/master 

## Description
Rather than save the entire output of the temporal downscaling models for each day, saving just the essential bits saves a lot of space and, as a result, time.  In order to do a low-memory replication of the model.frame function, all you need are the model coefficients, a callable formula for the model, a list of the factors/column names you need, and the contrasts.  See tdm_temporal_downscale_functions.R lines 123-158 & 189-225 to see where this has been implemented.  These portions now get called in lines 32-42 to have the same functionality as the original code (but so much faster!)

I also implemented the full set of code that would be necessary to add residual error if desired.

@jsimkins2 there are two spots I'm worried about: 1) was how we pull the betas to make Rbeta (what you have is quite different from my code); and 2) I could use a double check on precipitation.  Unless you sum precipitation to the day somewhere that I didn't see, I think there might be a unit error in your code and we would end up with a fraction of what it should be.

## Motivation and Context
Executing the temporal downscaling code was quite slow.  This is because the model .Rdata files were relatively large (~5 MB) so loading them hundreds of thousands of times was very slow.  Parsing these files down to just the essential information got them down to a couple kilobytes, so the code now runs ~200 x faster.

I don't think there's a specific issue about the speed issues, but they are improvements to #1356. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

I don't *think* anything should break, but Pecan's complicated, so I wouldn't guarantee it.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
@crollinson thanks a ton for the update!!

I think everything looks good to me, but one of your function declarations changed so you'll need to run ```make document``` and push up the updated modules/data.atmosphere/man/gen.subdaily.models.Rd to get Travis to stop complaining.

@jsimkins2 I'm going to wait for your 'Approve' to pull this since I want you to check the two things that Christy says she has concerns with.

**Comment by jsimkins2** [comment]
@crollinson Thanks for the updates! As for your concerns: 1) this explains why my recent runs have been rather jumpy, nice find!; and 2) Precipitation looks good to me!

@mdietze these changes all look good to me!

**Comment by crollinson** [comment]
Hold off on this pull request for the moment... Something is looking weird in my sub daily ensembles and I need to review it.  I'm going to use this opportunity to migrate everything to Pecan, so it might be a couple days... should I just close this pull request or keep it open?

**Comment by mdietze** [comment]
It's fine to keep it open. Just ping us when you ready.

**Comment by crollinson** [comment]
lots of commits about met are coming, so I'm going to go ahead close this PR so I don't cause a mess as I try to get everything sorted out

**Pull request closed without merging**
