### PR TITLE
Revise Docker documentation order and introduction

### PR DESCRIPTION
**Pull request by ashiklom**
## Description

- Fix documentation headings for Docker section so they're all under the "Docker" heading
- Make "Docker quickstart" the second section. I feel like "quickstart" things usually come before detailed descriptions.
- Add links to main Docker documentation and two YouTube tutorials I found _really_ useful for getting started with Docker
- Tighten up some of the text in the Docker introduction section. 

## Motivation and Context

As we move towards replacing the VM with Docker containers, we should try to have better documentation for it.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [X] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tonygardella** [comment]
@femeunier This documentation will be very important for us.

**Comment by ashiklom** [comment]
@tonygardella Feel free to add yourself as a reviewer. If you're going to be using these docs a lot, your input will be very useful, and I'd be happy to clarify anything in here that isn't clear.

That said, for starting out with Docker in general, I would _highly_ recommend the two video tutorials I added. They are quick (12 minutes each) but extremely effective at conveying the basics of how Docker and docker-compose work.

**Comment by tonygardella** [comment]
@ashiklom Sounds Good. Will definitely take a look at the videos.

**Comment by ashiklom** [comment]
#2114 includes this PR. If you want to merge them in pieces, you should start with this one. Or if you'd rather review both at the same time, just close this one and go straight to that one.

**Pull request merged**
