### PR TITLE
dump new tables PecanProject/bety#403 PecanProject/bety#491

### PR DESCRIPTION
**Pull request by robkooper**
dump missing tables from migrations up to BETY 4.15

### CODE REVIEW

**Comment by serbinsh** [comment]
@robkooper How do we implement this?  Just update PEcAn and when our systems run syncs everything is up to date or do we want to run anything manually?

**Comment by robkooper** [comment]
You can just copy the dump-bety.sh and load-bety.sh script and run that, no need to really update pecan. But until people use this new version of the scripts it will not copy the right tables.

**Comment by serbinsh** [comment]
Ok.  I pulled in the latest scripts which should start running with the cronjobs at BNL

[iPhone]

On Mar 17, 2017, at 10:40 AM, Rob Kooper <notifications@github.com<mailto:notifications@github.com>> wrote:


You can just copy the dump-bety.sh and load-bety.sh script and run that, no need to really update pecan. But until people use this new version of the scripts it will not copy the right tables.

**Comment by ankurdesai** [comment]
Same here (also updated Bety and migrated in the experiments table). Running sync job right now.

**Pull request merged**
