### PR TITLE
Break up read.settings

### PR DESCRIPTION
**Pull request by rykelly**
About to try to merge in some read.settings changes I've been using for my own work, and thought it would be a good time to clean up that messy file. Absolutely no functionality change, just (1) moved code around and (2) renamed some functions to follow my own "leading '.' means private function" convention. (Actually though I think some of those fns, e.g. `check.settings` should be exported, but we can talk about that another time...)

### CODE REVIEW

**Comment by mdietze** [comment]
@rykelly Betsy just rearranged read settings for the benchmark code. Therefore you have a lot of conflicts here. If you change anything in setting please make sure you don't break benchmarking

**Comment by rykelly** [comment]
Ah, OK. Let me take a look.

**Comment by bcow** [comment]
@rkelly I also didn't change any functionality, just moved a lot of the
functions into their own R scripts. Let me know if you have questions -
what was supposed you be a small pull request turned into a massive (and
I'm guessing somewhat impenetrable) one...

On Fri, Oct 28, 2016, 3:35 PM Ryan Kelly <notifications@github.com> wrote:

Ah, OK. Let me take a look.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PecanProject/pecan/pull/1150#issuecomment-257009152>,
or mute the thread

**Comment by rykelly** [comment]
No problem, Betsy. Just going through it now and it's kind of funny—we did almost exactly the same thing in that package. That's what I get for not pulling master often enough...

**Comment by rykelly** [comment]
So, @bcow, it looks like now you can use `read.settings` without actually running all the fix/check/update functions? That's great. Sorry I didn't notice that you'd done all this already...

**Pull request closed without merging**
