### PR TITLE
Small change to NLCD.R to output pixels count 

### PR DESCRIPTION
**Pull request by apourmok**

### CODE REVIEW

**Comment by robkooper** [comment]
Did you mean to checkin CanopyCover2NLCD.R~HEAD?

**Comment by apourmok** [comment]
No, I just added NLCD.R in data.remote.

**Comment by mdietze** [comment]
@apourmok could you remove the HEAD files and your local changes to .gitignore from this pull request?

**Comment by apourmok** [comment]
I removed those files.

**Comment by mdietze** [comment]
But you also deleted CanopyCover2NLCD.R, which you shouldn't have and will need to revert, and somehow one of those files got added to one of the subdirectory's .gitignore. Still needs cleaning up.

**Comment by apourmok** [comment]
I added the file and removed .gitignore in subdirectory.

**Comment by mdietze** [comment]
CanopyCover2NLCD.R is still missing and now it looks like the fix you made to NLCD.R is also missing as well.

The change you're introducing is so tiny, it might be simpler to just make that one change in a new, clean branch and try a new pull request, because at this point the volume of changes and discussion is probably 1000x larger than the fix.

**Comment by apourmok** [comment]
@mdietze done. It should be clean merge now from my clean branch.

**Pull request merged**
