### PR TITLE
change check_paths default to false

### PR DESCRIPTION
**Pull request by istfer**
check_paths in modify_ed2in is breaking remote runs, defaulting it to false

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [X] When possible
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by istfer** [comment]
I'll have another fix soon

write.configs is called on local machine

**Comment by ashiklom** [comment]
OK. If I were you, I would consider leaving the default for `modify_ed2in` as it is and, throughout `write.configs.ED2`, call `modify_ed2in(..., check_paths = check)`. That way, it'll be easier to add a remote-based toggle back in later.

**Comment by istfer** [comment]
ok did that

also I needed to force lat/lon to be numeric somewhere, otherwise it ends up being in `''` currently I put it in write.configs call, but it can also be in modify_ed2in, do you have a preference?

**Comment by istfer** [comment]
hey @ashiklom my ED2IN before and what is currently being written is different and breaks my runs

before
```
   NL%IED_INIT_MODE   =  3
   NL%SOIL_DATABASE     = '/projectnb/dietzelab/EDI/faoOLD/FAO_'
   NL%LU_DATABASE       = '/projectnb/dietzelab/EDI/ed_inputs/glu/'
```

now:
```
   NL%IED_INIT_MODE = 0
   NL%SOIL_DATABASE = ''
   NL%LU_DATABASE = ''
```

all these are passed via xml but overwritten by pecan_defaults in modify_ed2in, but when pecan_defaults == FALSE phenpath is left empty e.g. `NL%PHENPATH = '@PHENOL@'`

In write.configs.ed should these tags have been
```
      ed2in.text <- modify_ed2in(
      ed2in.text,
      IPHEN_SCHEME = settings$model$phenol.scheme,
      PHENPATH = "",
      IPHENYS1 = "",
      PIPHENYSF= "",
      add_if_missing = TRUE,
      check_paths = check
    )
```
instead of
```
    ed2in.text <- modify_ed2in(
      ed2in.text,
      PHENOL_SCHEME = settings$model$phenol.scheme,
      PHENOL = "",
      PHENOL_START = "",
      PHENOL_END = "",
      PHENPATH = "",
      add_if_missing = TRUE,
      check_paths = check
    )
```
I can either set pecan_defaults to false and make those changes or change the pecan defaults.

let me know what you think about these

**Comment by istfer** [comment]
No problem, new code is handy in many other ways ;)

but for now I'm going to set pecan_defaults to FALSE so that it won't break for others who work with different things for these tags:

```
  if (pecan_defaults) {
    ed2in[["IMETAVG"]] <- -1
    ed2in[["IPHEN_SCHEME"]] <- 0
    ed2in[["IPHENYS1"]] <- NA
    ed2in[["IPHENYSF"]] <- NA
    ed2in[["PHENPATH"]] <- ""
    ed2in[["IED_INIT_MODE"]] <- 0
    ed2in[["SOIL_DATABASE"]] <- ""
    ed2in[["LU_DATABASE"]] <- ""
  }
```

**Pull request merged**
