### PR TITLE
Add version fix for MERRA data download

### PR DESCRIPTION
**Pull request by KristinaRiemer**
MERRA data was not being downloaded for September 2020. This one month uses version 401 instead of 400 in its download URL. Thanks to @ashiklom for helping me figure this out! 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of .zenodo.json
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by dlebauer — CHANGES_REQUESTED** [review]
- Is this a temporary bug that warrants adding an exception for a single month, or is this something that will be resolved and could be marked as a temporary hack?
- please update CHANGELOG with description of the change

**Comment by ashiklom** [comment]
> Is this a temporary bug that warrants adding an exception for a single month, or is this something that will be resolved and could be marked as a temporary hack?

My guess is that this is a permanent change in the MERRA data that is specific to that month. I would be very surprised if GESDISC (the DAAC that manages MERRA data) would change the URL. I think this is the correct fix, and if they do decide to change the URL later, it will warrant a new PR.

I suspect the origin of this change is the MODIS outage that happened sometime around September 2020 that made the MERRA data assimilation pipeline do weird things, and there was some additional post processing they did to resolve those issues, hence version 401. But that's just a guess.

**Comment by mdietze** [comment]
This PR looks good to me. @KristinaRiemer looks like you just need to respond to @dlebauer request that you update the CHANGELOG

**Comment by dlebauer** [comment]
Ready to merge once checks pass

**Review by dlebauer — APPROVED** [review]

**Comment by KristinaRiemer** [comment]
Thanks for doing that @dlebauer!

**Pull request merged**
