### PR TITLE
Allow Docker services to be run as unprivileged user

### PR DESCRIPTION
**Pull request by julianpistorius**
## Description

Pass in the user and group IDs for the user starting the stack.

## Motivation and Context

Users want to be able to edit the files created in RStudio, etc. when not accessed through the Docker stack.

Partial (?) fix for: https://github.com/PecanProject/pecan/issues/2572

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) #2572
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

 

## Notes for reviewers

We changed the web container Dockerfile. Please rebuild the web Docker image just before you run `docker-compose up -d`:

```bash
 docker build -t pecan/web:develop -f docker/web/Dockerfile .
```

### CODE REVIEW

**Comment by julianpistorius** [comment]
@robkooper FYI I'll make a separate PR with the `${BOUND_IP:-127.0.0.1}` changes once this PR is merged.

**Comment by KristinaRiemer** [comment]
Should @istfer also review this?

**Comment by istfer** [comment]
Sure, I'll test it as well

**Comment by istfer** [comment]
Couple of things after I tried it after working with Julian's branch:

My bety, thredds and web container kept crashing after I bring the stack up. Here were the outputs from logs:
```
docker-compose logs thredds
...
thredds_1        | chown: changing ownership of './webapps/thredds/tdsDap.css': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/thredds.jpg': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/threddsIcon.gif': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/threddsSmall.jpg': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/unidataIcon.gif': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/unidataLogo.gif': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/unidataLogo.jpg': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds/upc.css': Operation not permitted
thredds_1        | chown: changing ownership of './webapps/thredds': Operation not permitted
thredds_1        | chown: changing ownership of './webapps': Operation not permitted
thredds_1        | chown: changing ownership of './work': Operation not permitted
thredds_1        | chown: changing ownership of '.': Operation not permitted
```

```
 docker-compose logs web
...
web_1            | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
web_1            | no listening sockets available, shutting down
web_1            | AH00015: Unable to open logs
web_1            | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.17. Set the 'ServerName' directive globally to suppress this message
web_1            | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
web_1            | no listening sockets available, shutting down
web_1            | AH00015: Unable to open logs
web_1            | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.17. Set the 'ServerName' directive globally to suppress this message
web_1            | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
web_1            | no listening sockets available, shutting down
web_1            | AH00015: Unable to open logs
```
```
docker-compose logs bety
bety_1           | Start running BETY (unicorn)
bety_1           | I, [2020-08-04T10:41:18.614497 #1]  INFO -- : Refreshing Gem list
bety_1           | bundler: failed to load command: unicorn (/usr/local/bundle/bin/unicorn)
bety_1           | PG::ConnectionBad: FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
```

bety container crash is something I have experienced on linux since the beginning (e.g. #2658 ) so I stopped containers changed the permissions to the volume directory and restarted the containers. That solved the bety container problem. Then I was able to give the sipnet run via:

```
docker-compose exec executor bash
# inside the container
cd /pecan/tests
R CMD ../web/workflow.R docker.sipnet.xml
```
Btw while doing it I saw this `I have no name!@6a75eda90a96:` when I executed these commands.

I couldn't test if I can resubmit runs or interact with files from within RStudio because I was unable to connect localhost:8000 `can’t establish a connection to the server at localhost:8000`. Then, I tried localhost:8080 as well, and I got `channel 3: open failed: connect failed: Connection refused` from terminal , and `The connection to the server was reset while the page was loading. from the browser.` Not sure if this is now due to the crashing of the web container, probably. But dunno how to solve it, do I need to change something else in docker-compose.override or in .env?

**Comment by julianpistorius** [comment]
@istfer My apologies. I forgot to mention that we changed the web container Dockerfile. Please rebuild the web Docker image just before you run `docker-compose up -d`:

```bash
 docker build -t pecan/web:develop -f docker/web/Dockerfile .
```

**Comment by istfer** [comment]
Got it, I hadn't realize that there was a Dockerfile change.

After rebuilding the image and following the instructions, my bety container keeps crashing, I get this `psql: FATAL:  no pg_hba.conf entry for host "172.31.0.17", user "bety", database "bety", SSL off ` but not sure why

**Comment by julianpistorius** [comment]
@robkooper Other than rebasing and resolving conflicts, what would you like me to do to help review this?

**Comment by dlebauer** [comment]
@istfer did you ever resolve the issue mentioned above in https://github.com/PecanProject/pecan/pull/2669#issuecomment-670497121?

**Comment by istfer** [comment]
> @istfer did you ever resolve the issue mentioned above in [#2669 (comment)](https://github.com/PecanProject/pecan/pull/2669#issuecomment-670497121)?

Sorry, no @dlebauer I haven't played with the container tests for a while

**Pull request merged**
