### PR TITLE
Minor.rtm.update

### PR DESCRIPTION
**Pull request by serbinsh**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by serbinsh** [comment]
@ashiklom Where I put this copy command, will that run every time or just at first runtime?

If always, where could I put it so it only copies when initially creating the output dirs?  Or should I just look for the file each time and only copy if it isn't there?

**Comment by ashiklom** [comment]
As it is, you will do the copy and overwrite operation every time `EDR` is called, which of course is thousands of times for an inversion.

I would suggest something like:

```r
soil_path <- paths$soil
if (is.null(soil_path)) {
    soil_path <- system.file(...)
}
if (!is.na(soil_path)) {
    file.copy(soil_path, output_dir, ...)
}
# And the same for the other path.
```

This allows you to force the copy operation to be off by passing a `paths` list where `soil = NA`, to pass a custom soil path via `soil = "/your/path",` or to use the default by leaving `soil` unset or explicitly set to `NULL`.

**Comment by serbinsh** [comment]
I will make the change before we commit

**Comment by ashiklom** [comment]
I implemented the changes I suggested. Haven't had a chance to test this yet, but I think it's good to go.

**Pull request merged**
