### PR TITLE
install specific version of dbplyr

### PR DESCRIPTION
**Pull request by robkooper**
This installs version 1.3.0 of dbplyr. This should fix the build problems. There is an issue #2349 that tracks the progress of making PEcAn work with the latest version of dbplyr again.

## Review Time Estimate

- [X] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by infotroph** [comment]
@robkooper Looks like we'll need to beat devtools::install_deps into submission too: https://travis-ci.org/PecanProject/pecan/jobs/528879594#L2990

**Comment by tonygardella** [comment]
Still getting that dang error:
```
2019-05-06 16:36:00 DEBUG  [PEcAn.workflow::do_conversions] : 
   updated met path: /home/travis/sipnet_unk/niwot_tutorial.clim 
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "AS"
LINE 4: WHERE ("name" = ('temperate.coniferous' AS "name", '/home/tr...
                                                ^
)
Calls: <Anonymous> ... dbSendQuery -> dbSendQuery -> postgresqlExecStatement
----------------------------------------------------------------------
TEST travis.sipnet.xml FAILED (ERROR IN STATUS)
----------------------------------------------------------------------
TRAIT	2019-05-06 16:36:00	2019-05-06 16:36:00	ERROR	
travis_time:end:08e5ac87:start=1557158398081664864,finish=1557160560918394444,duration=2162836729580
[0K[31;1mThe command "scripts/travis/script.sh" exited with 1.[0m
```

**Comment by robkooper** [comment]
Looks like it might be installed as the default install of R, trying to look at that now.

**Comment by robkooper** [comment]
2 problems, 1.4.0 is installed by default using an apt-get install by the R travis build. I force it down to 1.3.0 but `devtools::install*` will have upgrade=TRUE by default and it ignores the version numbers in DESCRIPTION and will always default to the latest version.

**Pull request merged**
