### PR TITLE
Gh 454 delete history

### PR DESCRIPTION
**Pull request by robkooper**
This will also remove corresponding entries from ensembles, runs and inputs_runs.

### CODE REVIEW

**Comment by mdietze** [comment]
@robkooper if I understand this code correctly, it looks like it will orphan all the files associated with the run(s) and analyses when the workflow is deleted. I think we want to delete the files as well.

**Comment by robkooper** [comment]
Do yo mean the physical files on disk? If so we can only delete those files that the user who is running it has access to.

Do you want to delete the posteriors as well? Right now these are associated with a PFT. We have a table (posteriors_ensembles) that could link them to an ensemble but we are not using it right now.

**Comment by mdietze** [comment]
Yes, I mean the physical files on disk.

Would it be hard to give the user a warning if they don't have permissions to delete the files? I think folks should at least be made aware that they're going to create orphan files if they delete database records.  The web user should have permissions to delete files created by the web interface, which I think is the biggest problem. We'll also encounter the issues of deleting files on remote servers, as well as not wanting to delete records that belong to a different PEcAn instance, but I think we can punt on that for today.

For the Posteriors, we need to be careful to not delete posteriors that are used in other analyses. With update=AUTO as the default, most workflows shouldn't be generating Posteriors, and we definitely don't want to delete a Posterior that came from another workflow. That said, we do have a Posterior proliferation problem along side our dud Runs proliferation problem, but I think that's probably best left to another Issue.

**Comment by dlebauer** [comment]
Is this a case where the postgres ['cascade delete']( function would simplify the code by deleting all records that link to the row's primary key

From documentation (http://www.postgresql.org/docs/8.2/static/ddl-constraints.html)

    CASCADE specifies that when a referenced row is deleted, row(s) referencing it should be automatically deleted as well.

**Comment by robkooper** [comment]
Cascade does not work because the constraints are not setup to cascade on delete.

**Comment by dlebauer** [comment]
I know it is not yet implemented, but if the behavior is always desired it
seems like something that postgres is set up to do much more easily and
consistently than pecan. And a database level cascading delete wouldn't
require the web interface.

**Comment by robkooper** [comment]
If I remove the last ensemble that references a posterior, should that posterior also be removed? Or do we want to keep that around so the next time the user runs that pft the posterior does not have to be computed?

**Comment by mdietze** [comment]
I think you delete the posterior if the last ensemble is deleted and this isn't the most recent posterior and the posterior doesnt have any children. Conceptually the last ensemble and no children should be synonymous, but it wouldn't hurt to check. This all gets complicated if you're trying to delete runs that are part of a larger data assimilation, but in practice I think almost all deleting will occur on runs that were duds so our first pass doesn't need to be super paranoid

**Comment by robkooper** [comment]
Now also deletes posteriors.

**Comment by robkooper** [comment]
@mdietze i think this is ready now.

**Pull request merged**
