### PR TITLE
Move ED2 internal data to unexported sysdata.rda

### PR DESCRIPTION
**Pull request by Aariq**
## Description
This moves history.csv and soil.csv files to `models/ed/data-raw/` which is in .Rbuildignore and instead includes them in sysdata.rda which is unexported by default.  These data files are necessary for functionality of `write.configs.ed.R` but do not need to be exported.

## Motivation and Context
Solves failing checks in #2985 

## Review Time Estimate

- [x] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Aariq** [comment]
Failing test is undocumented dataset pftmapping.  This is documented in PR https://github.com/PecanProject/pecan/pull/2985.  Together, these two PRs should fix all (new) warnings for PEcAn.ED2

**Comment by dlebauer** [comment]
Thanks for proposing this; I'm not familiar with the convention of using a data-raw folder; is this preferred over inst/extdata?

**Comment by Aariq** [comment]
The approach I took was the one suggested in the R Packages book (https://r-pkgs.org/data.html).  They mention inst/extdata in the context of vignettes in that it's useful if you want to show examples of reading in data.  I can certainly try it though and see if `devtools::check()` complains.

**Comment by Aariq** [comment]
> That also gives us extra flexibility on the format of the file; i.e., we can do a more standard CSV format, or other formats parsed in specific ways as appropriate.

I don't think there is any limitation on file format with the proposed solution (or any solution for this really).  A .rda file can hold any number of any kind of R objects and they can be read in and parsed in different ways in sysdata.R so this reading in and parsing doesn't have to happen inside of functions.

**Review by dlebauer — APPROVED** [review]
@Aariq I share @ashiklom 's concern that the sysdata.R needs to be rerun when the files are updated. However, these inputs seem like they won't change except when adding a new version of ED2.

And it does appear to follow recommendations / best practices in the textbook.

The other recommended option for internal data is to use dput and paste it in the code. That option is appealing in its simplicity but it also has downsides of not being easily readable.

**Comment by Aariq** [comment]
Ok, so I think what I'll try to do then is merge this PR into #3006 since they have complimentary changes that, together, should result in passing checks.

**Pull request merged**
