### PR TITLE
Change R version to 3.5 in .travis.yml {WIP}

### PR DESCRIPTION
**Pull request by tonygardella**
## Description
Change R to 3.5 in travis.yml

## Motivation and Context
Need to upgrade R version in TRAVIS build to 3.5. 
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tonygardella** [comment]
Failed with:
```
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
```

**Comment by robkooper** [comment]
This is the list of dependencies I use in Docker builds. This however does not run tests:

    && apt-get -y --no-install-recommends install \
       jags \
       time \
       libgdal-dev \
       librdf0-dev \
       libnetcdf-dev \
       libudunits2-dev \
       libx11-dev \
       libgl1-mesa-dev \
       libglu1-mesa-dev \
       libfreetype6-dev \

**Comment by ashiklom** [comment]
Probably won't fix it, but try giving the full version number (`3.5.0`), as discussed [here](https://github.com/travis-ci/travis-ci/issues/9654).

**Comment by tonygardella** [comment]
Closing in favor of #2264

**Pull request closed without merging**
