### PR TITLE
Least squares inversion, block sampling, and spectral response functions in RTM module

### PR DESCRIPTION
**Pull request by ashiklom**
Added both of these features to the RTM package. Also updated documentation.

The block sampling (in `invert.slow.R`) might be a handy reference for anyone that wants to implement it elsewhere.

### CODE REVIEW

**Comment by robkooper** [comment]
is this needed for flux camp?

**Comment by mdietze** [comment]
No, not needed for camp

**Comment by ashiklom** [comment]
All the commits I just added are related to sensor spectral response functions.

**Comment by ashiklom** [comment]
Oops, just realized there are unnecessary data files in here. I'll get on removing those.

**Comment by ashiklom** [comment]
For some reason, all my commits were duplicated after I tried to remove the spectral data. I'm gonna clean this up and then submit a new pull request.

**Comment by ashiklom** [comment]
I removed the data, but looks like we're stuck with duplicated commits. I've learned my lesson that you should not perform things like "git rebase" or "git filter-branch" on commits in a public repository. Sorry about that!

**Comment by mdietze** [comment]
@robkooper could you check whether the unnecessary data files were removed correctly so they aren't carried around by the repository. Otherwise looks fine to commit.

**Comment by robkooper** [comment]
Are the following files needed and do they need to be rdata, can they be a csv?

Looking at the commits, I think that the following files are added and deleted:
- modules/rtm/data/aviris.wl.RData
- modules/rtm/data/bandwidth.chrisproba.RData
- modules/rtm/data/fwhm.aviris.classic.RData
- modules/rtm/data/fwhm.hyperion.RData
- modules/rtm/data/rsr.avhrr.RData
- modules/rtm/data/rsr.landsat.RData
- modules/rtm/data/rsr.modis.RData
- modules/rtm/data/rsr.viirs.RData

And only the following 2 files are added:
- modules/rtm/data/raw.sensor.data.RData
- modules/rtm/data/sensor.rsr.RData

Does that sound right? To be hones (I just briefly scanned) the files seem to be around 8KB or so, which is pretty safe to ignore (they are not MBs).

**Comment by ashiklom** [comment]
I originally had separate data files for each sensor, but then combined
them into a single file. Each data file just has a matrix, 2100 rows by the
number of bands.

I can go back and purge them from the history but as Rob pointed out, they
are pretty small.

Alexey Shiklomanov
Boston University

**Pull request merged**
