### PR TITLE
 1) docker-compose -v changed to docker compose version and 2) all do…

### PR DESCRIPTION
**Pull request by ecamo19**
…cker-componse lines changed to docker compose

## Description
Currently, the Docker installation section in PEcAn's manual contains two lines that are incorrect according to the [Docker documentation](https://docs.docker.com/compose/install/):

1) docker-compose -v which should be changed to __docker compose version__
2) docker-compose where the __"-"__ should be removed and change the line to __docker compose__  

## Motivation and Context

If the command docker-compose is used it will return the error "_command not found: docker-compose_" which can be confusing to new users with no experience in docker 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of .zenodo.json
- [ ] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by robkooper — APPROVED** [review]

**Comment by Aariq** [comment]
Interestingly, `docker compose version` returns something different: `Docker Compose version v2.6.0`

**Comment by ecamo19** [comment]
> Interestingly, `docker compose version` returns something different: `Docker Compose version v2.6.0`

Hi Eric, I found that if you run docker-compose on a Linux-based machine you will get an error so that is why I did the pull-request

**Comment by Aariq** [comment]
> > Interestingly, `docker compose version` returns something different: `Docker Compose version v2.6.0`
> 
> Hi Eric, I found that if you run docker-compose on a Linux-based machine you will get an error so that is why I did the pull-request

Ah ok.  Let me just quickly check that these updated instructions still work on macOS.

**Comment by Aariq** [comment]
Works!  I guess `docker compose` is the newer version of `docker-compose`, so good to change this! https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

**Review by Aariq — CHANGES_REQUESTED** [review]
Hey Erick, I just noticed that there are some references to `docker-compose` in other places as well.  I figure it would be good to change them all at once. Doing a find in all files (cmd + shift + F in RStudio), I see `docker-compse` in the following places besides 01_install_pecan.rmd:

- book_source/03_topical_pages/94_docker/07_migrate.rmd, 00_docker_index.Rmd, 09_rabbitmq.Rmd, 05_building_images.Rmd, 02_quickstart.Rmd, 03_architecture.Rmd
- book_source/03_topica_pages/03_pecan_xml.Rmd
- docker/docker-compose.example.yml
- docker/env.example
- DEV-INTRO.md
-

**Comment by Aariq** [comment]
I've tested the changes to the install instructions that are already in this PR and they work.
I'm having second thoughts about changing `docker-compose` to `docker compose` everywhere since there may be some [compatibility issues](https://github.com/docker/compose/tree/v2#about-update-and-backward-compatibility) with migrating to the new version of Docker Compose (`docker compose`).

**Pull request merged**
