### PR TITLE
Viz dependency cleanup: Delete unused `points2county`, drop excessive Depends

### PR DESCRIPTION
**Pull request by infotroph**
## Description
* Deletes `PEcAn.visualization::points2county` with no deprecation period. It's unused in our codebase, allows us to drop dependency on the `earth` package (which requires R>=3.5 and adds a number of fairly heavyweight dependencies of its own), and @dlebauer says there are now better ways of doing this interpolation task.
* Cleans up the PEcAn.viz DESCRIPTION file while I'm there:
  - Removes seven (!) dependencies that are, as far as I can tell, completely unused.
  - Moves three more from Depends to Imports -- their functions are already called in `::` form throughout the package.
  - Finishes converting author list from Author/Maintainer form to Authors@R form.

## Motivation and Context
The proximal reason for this cleanup is that dependency `earth` has updated to require R 3.5, thus breaking Travis builds using R 3.4. The Travis build is being updated to use a newer R in #2264, but since we weren't actually using `earth` for anything, why drop support for R 3.4 sooner than we have to?

## Review Time Estimate

- [x] Immediately
- [ ] Within one week
- [ ] When possible
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by infotroph** [comment]
@KristinaRiemer Tagging you because we're paired for code review this week. If you have the bandwidth for it, I'd especially appreciate verification that the removed packages were truly unused.

**Comment by KristinaRiemer** [comment]
@infotroph can do. I'm going to get in touch with you on Slack.

**Comment by tonygardella** [comment]
@KristinaRiemer was about to merge but saw you were going to review and get in touch so I'll wait. I'll merge after your review.

**Comment by KristinaRiemer** [comment]
All the visualization functions that I was able to run didn't produce any errors. I couldn't run `plot.netcdf()` because I don't have an hdf5 file of the correct format and also couldn't run `create_status_page()` because I'm not sure how to get the config.php file it requires. If that's fine, I'd say go ahead with the merge.

**Comment by infotroph** [comment]
`plot.netcdf` is working for me:

```
PEcAn.visualization::plot.netcdf("~/Desktop/pecan_test/biocro_20180803/pecan/out/ENS-00010/2004.nc", yvar="NPP", xvar="time", width=800, height=600, filename="~/Desktop/pecan_ncplot_test.png", year=2004)
null device 
          1 
Warning message:
In readPNG(system.file("favicon.png", package = "PEcAn.visualization")) :
  libpng warning: iCCP: known incorrect sRGB profile
```

Haven't seen that warning before, but it doesn't look like a library issue to me -- maybe my local libpng is old. I'm happy ignoring it if y'all are.

**Pull request merged**
