### PR TITLE
Met Corrections

### PR DESCRIPTION
**Pull request by crollinson**
A few slight corrections to 3 of the met processing scripts:
1) in my own download.NLDAS and download.GLDAS I noticed the time stamps were off.  This version corrects those
2) changed the file path in download.GDLAS to default to the coarser spatial resolution but longer temporal extent repository.
3) corrected ntime in download.CRUNCEP_Global.R  @jsimkins2 @mdietze  -- The current time left me an hour short every year when working on my bias-correction & downscaling code.  Some scripts I have that worked with the raw grids did not provide any evidence that this should be true, so I took the liberty of correcting it.  Please let me know if there's some quirk of CRUNCEP that I'm missing where we should be ignoring either the first or last hour of every year.

### CODE REVIEW

**Comment by mdietze** [comment]
Can you verify that cruncep is working within the workflow. It was n-1 because that's what the server was returning to us

**Comment by crollinson** [comment]
I can try testing both versions in the full Pecan workflow in the next day or so.  

Right now I can verify that both versions do successfully extract & write data at least for Harvard Forest and UNDERC. Line 65 in download.CRUNCEP is where things are currently set up so that you leave off the last date and allowed the (n-1) version to function.

I only noticed the problem when I tried matching the extracted data to the expected time stamps when preparing data for bias correction.  When I extract the data from the raw CRUNCEP grids I have stored locally on geo, the expected number of points (n).

**Comment by jsimkins2** [comment]
@crollinson  Hey Christy, I found another error in the CRUNCEP code. Could you add a +1 after that lat_trunc and lon_trunc like so?

  lat_trunc = floor(2*(90-as.numeric(lat.in)))**+1**
  lon_trunc = floor(2*(as.numeric(lon.in)+180))**+1**

While the algebra is correct, the array begins at 0 for the OPeNDAP binary file, so the lat/lon coordinates have been off by 1. I found the same error with my GFDL code and figured I'd ask you to make this change while this pull request is still open

**Comment by mdietze** [comment]
As per the conversation in today's PEcAn telecon, we're going to merge the PR and then punt the integrated NLDAS/GLDAS testing into the the VM release candidate. @crollinson could you coordinate with @tonygardella on that?

**Pull request merged**
