### PR TITLE
fix scratch dir

### PR DESCRIPTION
**Pull request by robkooper**
- make sure scratch dir exists
- prepend run with workflow id, this will make sure all runs for a
workflow are in the same folder.

### CODE REVIEW

**Comment by serbinsh** [comment]
@robkooper Thanks!  Would you like me to check that this works on my end first before we merge?  Or were you just giving me a heads up?

**Comment by robkooper** [comment]
@serbinsh can you check first to see if this does the trick

**Comment by serbinsh** [comment]
@robkooper checking on this now

**Comment by serbinsh** [comment]
@robkooper it looks like that worked!  I suppose for models like ED2 with intensive I/O and on sysytems like ours (shared NFS storage with local disc space as well) this is a decent option but will need to be enabled in each models write.configs.MODEL code

**Pull request merged**
