### PR TITLE
[GH Actions] remove special installation for processx

### PR DESCRIPTION
**Pull request by infotroph**
No longer needed because 3.5.2 is available from CRAN now.

### CODE REVIEW

**Comment by infotroph** [comment]
...Well, OK, it's on CRAN but not yet in the Depends docker image, presumably because that uses date-locked snapshots from RSPM. 

@robkooper is there a way to prompt the image to update or should we hold this PR until the new processx shows up automatically (presumably when we switch to testing with a newer R release)?

**Comment by robkooper** [comment]
we use the date limited to make sure we are building with a consistent version of packages, and not what CRAN thinks is the right set of packages.  So yes, I think we can remove it when we bump versions. Should we build using 4.0 and 4.1 instead?

**Comment by infotroph** [comment]
@robkooper Yeah, that makes sense to me. How much trouble would it be to also test against R-devel? In an ideal world I'd like to add that, but I realize that's kinda the opposite of consistent versions and I don't have a sense how much trouble it adds to the Docker stack.

**Comment by robkooper** [comment]
as long as we don't require that to pass, I think it is ok.

**Comment by infotroph** [comment]
ping @robkooper -- I think this should be a quick review

**Review by robkooper — APPROVED** [review]

**Pull request merged**
