### PR TITLE
Adjust Allometry based on DBH range of interest

### PR DESCRIPTION
**Pull request by crollinson**
Sapling-specific allometry codes in the Jenkins database can cause unreasonable estimates of of large trees.  I have added additional arguments to the allometry script to 
1) remove equations with a maximum DBH below the specified DBH cutoff (or min above the max)
2) adjust sample sizes so that equations that include observations in the range of interested, but with many outside of the dbh threshold are given less weight.

There is also an example script for using the allometric database (developed in conjunction with R. Alexander) that can/will be adapted into an allom.predict function in the future.

### CODE REVIEW

**Comment by mdietze** [comment]
@crollinson Overall this looks good, but why did you delete modules/allometry/data/Table3_GTR-NE-319.v2.csv?

**Comment by crollinson** [comment]
I'm assuming you're talking about the 2nd commit listed where I added Ross's equations.  Did it really get deleted and this pull will completely remove it?  It's still showing up all of my files and the apparent deletion might be an artifact of overwriting with an older file or something.

**Comment by mdietze** [comment]
Yes, if you look under the Files Changed tab you'll see that it's deleted completely in your pull request and there's no new file in its place.

**Comment by dlebauer** [comment]
Don't the Jenkins equations all come with the ranges for which they are
valid?

**Comment by crollinson** [comment]
@dlebauer The table does have those ranges.  However, including the sapling-specific equations when trying to create an overall equation to predict biomass for mostly adult trees can result in some really wonky biomass estimates.  Particularly in a case where the sapling equation is the only available biomass equation or if it's carrying more weight than an adult allometry equation.  There have been a couple groups working with allometry who have encountered this problem recently (including @alexanderm10 and Adrien Finzi).  Adding these dbh ranges will let you either exclude sapling (or large-tree only) equations or at least give them less weight in the overall species- or pft- allometry equation.

**Pull request merged**
