### PR TITLE
Create ED2INv2.2.0

### LINKED ISSUE #2143: `ED2IN.git` is out of date
**Describe the bug**
New versions of ED need the following additional ED2IN tags, which are missing from the current version of ED:

```
IOOUTPUT, it must be 0 (none) or 3 (HDF5)
PLANT_HYDRO_SCHEME, it must be between -2 and 2
ISTOMATA_SCHEME, it must be between 0 and 1
ISTRUCT_GROWTH_SCHEME, it must be between 0 and 1
TRAIT_PLASTICITY_SCHEME, it must be between 0 and 2
```

**To Reproduce**
Build a fresh ED2 Docker container (which pulls from Git) and try to do a run via the PEcAn web interface.

**Expected behavior**
Model should run.

**Machine (please complete the following information):**
 - Docker

### PR DESCRIPTION
**Pull request by dlebauer**
Got started on v2.2.0 ED2IN fixes #2143

based on ED2IN.git

still need to finish finding and replacing variables

## Description

Starting to make a new version of ED2IN for v 2.2.0

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
David has suggested [getting rid of the ED2IN.git](https://github.com/PecanProject/pecan/pull/2599). I think it makes sense to have only ED2IN files that map to specific ED2 versions, instead of having an ED2IN that's a moving target that might not actually be compatible with the git master version of the model (as is currently the case).

**Comment by robkooper** [comment]
That is fine with me, but lets make sure it is discussed in slack pecan channel also. We should also remove the docker image in that case from the docker.sh (and I will remove it from docker hub).

**Comment by dlebauer** [comment]
I have removed ED2IN.git and renamed the new file ED2IN.2.2.0

**Comment by robkooper** [comment]
remove the {wip} from the title when pull request is ready.

**Comment by dlebauer** [comment]
I think it is ready

**Comment by dlebauer** [comment]
I've added a record to the models table in BETYdb where model_name = ED2.2 and revision = 2.2.0

**Comment by dlebauer** [comment]
the test suite worked. merging:

```sh
./docker.sh -i test 
PECAN_VERSION=test docker-compose up
```

**Comment by mdietze** [comment]
@dlebauer (1) I don't see the new bety record in my DB -- which machine number do we all need to be syncing to grab that? (2) The model type should just by ED2 not ED2.2 otherwise PEcAn will look for a (nonexistent) PEcAn ED2.2 package.

Looking through the database I also noticed that there were multiple ED2 git entries from different machines, suggesting that duplicate entries for the same model were created, which breaks BETY's ability to know these are the same model across different machines. It's important that others _sync_ this new ED2 version rather than adding it locally.

**Comment by dlebauer** [comment]
@mdietze this is the record: https://www.betydb.org/models/14 - all need to sync w/ machine 0:

image

**Comment by dlebauer** [comment]
Until the databases sync, anyone can use this to add the ED2.2 model to their instance (will be over-written with the same on sync)

```sql
INSERT INTO "public"."models"("id", "model_name", "revision", "parent_id", "created_at", "updated_at", "modeltype_id") VALUES (14, 'ED2.2', '2.2.0', 5000000001, '2020-05-06 22:54:49.048066', '2020-05-06 22:54:49.048066', 1);
```

**Pull request merged**
