### PR TITLE
add documentation about ED and singularity

### PR DESCRIPTION
**Pull request by robkooper**
Document how to run ED in singularity. This is based on discussion in #containers channel in slack.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
Since it looks like this specific example is able to build an ED2 binary successfully, but has an ED2IN error, it would be good to update the documentation once that error has been found/fixed so that the documentation has a clean example.

**Comment by KristinaRiemer** [comment]
I'm not seeing the bash or file chunks in the book? https://pecanproject.github.io/pecan-documentation/develop/models-singularity.html

**Comment by robkooper** [comment]
click on the header with >

**Comment by KristinaRiemer** [comment]
This is what that page looks like for me: 
Screen Shot 2020-02-13 at 9 12 19 AM

I clicked on "bash script to install required files" text to get the code chunk to show: 
Screen Shot 2020-02-13 at 9 12 37 AM

I only knew to do that because you suggested clicking. Is there a way we can indicate that people should do that?

**Comment by robkooper** [comment]
Interesting, in my case it has a little triangle in front of it. I can add some text saying "click here to expand"

**Pull request merged**
