### PR TITLE
Add Setaria as genus for running BioCro

### PR DESCRIPTION
**Pull request by KristinaRiemer**
## Description
Added the genus *Setaria* to `call_biocro`

## Motivation and Context
We are using PEcAn to run BioCro on *Setaria viridis* for a project

## Review Time Estimate
- [ ] Immediately
- [x] Within one week
- [ ] When possible
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by infotroph** [comment]
I assume this was considered already, but to check: Am I right that we want to eventually move away from having PEcAn-specific model parameter files in `models/biocro/inst/extdata/defaults/` and therefore it's intentional that this PR doesn't add a Setaria file there?

**Comment by KristinaRiemer** [comment]
Oh, I somehow missed those genus-specific files when I was searching. Thoughts @dlebauer?

**Comment by dlebauer** [comment]
good catch @infotroph yes, we will need to have a extdata/defaults/setaria.xml file. We can start by copying the panicum.xml file. 

@infotroph you are correct that we want to move away from pecan specific defaults but will wait until we start using v1.0 for that!

**Comment by KristinaRiemer** [comment]
Okay, I've added that file. The only thing I changed between Sorghum and Setaria was the genus tag, should anything else be different?

**Pull request merged**
