### PR TITLE
satellitetools by Olli

### PR DESCRIPTION
**Pull request by ayushprd**
## Description

satellitetools developed by (Olli Nevalainen, FMI) contains python scripts to download Sentinel 2 data from Google Earth Engine. It also has an python implementation of the SNAP toolbox, which is used to perform computation on the downloaded data. 

Original repository: https://github.com/ollinevalainen/satellitetools 

## Motivation and Context

These codes will be used while extending the remote data module.

Please note that **Olli is the author** of satellitetools. These are not my own codes and I have not contributed to it by any means whatsoever. I am pushing it because my upcoming PR's use satellitetools as an external library.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
If this code exists in another repository, why is it being added to the PEcAn repo rather than just being a dependency? This seems to be redundant and will result in the two versions diverging.

**Comment by istfer** [comment]
It is intended to diverge, we were thinking of making use of these existing code by @ollinevalainen but it is probable that the code will need modifications (not necessarily benefiting Olli's needs). 

@ayushprd was pushing it as it is first then he will change it as he goes, it was just more convenient to review his stepwise progress with respect to the original code this way.

**Comment by istfer** [comment]
@ayushprd do we need all the .nc files in the output directory? Do we need that directory at all?

**Comment by istfer** [comment]
Likewise Ruukki files are quite project specific, can we remove them as well? In general, it would be better to keep the absolute minimum rather than pushing everything

**Comment by ayushprd** [comment]
I should've removed those, will do. Are those causing the checks to fails @istfer ?

**Comment by mdietze** [comment]
As @istfer noted, there seems to be a lot of project-specific example files in this PR (there's also xlsx files in there). If you just delete them, they'll remain in the repo forever. I'd suggest starting a new PR from a fresh branch where you only add the filed you actually need.

**Comment by istfer** [comment]
Thanks @mdietze that's a good point.

@ayushprd can we just keep it to the NDVI retrieval? We need to think about how to handle SNAP auxiliary data files, even though they are the training data for the algorithm and part of the module mechanics, they also shouldn't live in the repository

**Pull request closed without merging**
