### PR TITLE
Better Filenames (replaces gh-507)

### PR DESCRIPTION
**Pull request by ryankelly-uiuc**
This includes further updates to prevent pecan from overwriting files. 

In the version I'm pushing here, few files retain generic filenames. One of the exceptions is samples.Rdata, but most of its pertinent information is now duplicated in ensememble.XXX.Rdata or sensitivity.XXX.Rdata, where XXX is the unique ensemble id. The trait.XXX and prior.XXX outputs of get.trait.data() have generic names too still, but I figure as the first step in the analysis there's less of a need to be able to save multiple versions. 

I did not add additional variable + time tags to filenames, as suggested by @mdietze . When I looked into it, many of the SA and ensemble files have this already, and the rest are now identified by ensemble ID. So, nothing important will be overwritten if analyses are redone for different years or variables. But @mdietze , let me know if you meant that you'd like files that are identified by ensemble ID to *also* include variable/year in the filenames just for convenience.

### CODE REVIEW

**Comment by mdietze** [comment]
Ryan, yes I meant that files would have ensemble ID _and_ years + variable. For files that do not have information extracted from the runs for specific years and variables this is superfluous, but for things like the sensitivity, ensemble, and variance decomposition results these numbers do vary WITHIN AN ENSEMBLE depending on the extraction. So, for example, samples.Rdata does depend upon the ensemble.id but not the years and variables since it stores the inputs to these analyses. By contrast, the following DO need the variable and year info to be unique: ensemble.Rdata, ensemble.ts.Rdata, ensemble.ts.analysis.results.Rdata, sensitivity.Rdata, sensitivity.results.*.Rdata,

**Comment by ryankelly-uiuc** [comment]
Ah, OK I see what you mean. However, it looks like those files were meant to be able to contain analyses on multiple variables. On the other hand, in my tests that doesn't seem to actually work, and I see that run.sensitivity.analysis and run.ensemble.analysis output variable-specific filenames based on only the first variable name (in a vector that theoretically could have multiple). Do you want me to follow suit, and/or change the code so that if multiple variables slated for sensitivity/ensemble analysis, they each go to separate files?

**Comment by mdietze** [comment]
Ryan, whether its true or not that you can set up a SA, EA, or VD to have multiple variables if you run it once, it's still true that if you run it a second time it will overwrite the original file, which is the problem that I was having that lead me to add variable name and years to the file name.

If someone does the original analysis on multiple variables it probably would be best to split the files by variable, if that's not too much of a hassle. Alternatively, the code could be modified to open the existing file and add new analyses, but then we'd still need a way to indicate date ranges internally within that file (looking at uncertainty over different time scales has been pretty common). Either is fine with me.

**Comment by ryankelly-uiuc** [comment]
Gotcha. I think separate files is a little easier to implement, so currently planning to go that route. Because of the way the code's set up now (i.e., inconsistently handling attempts to process multiple variables at once), I also think it's easiest to restrict all of these analyses to one variable at a time, but add arguments for variable and year to the functions so it's easy to re-run them manually for different combinations. Output from each will go to uniquely named files, and putting them within a loop would be easy. In fact, the ability to do multiple variables / times in one go could then be added with a simple wrapper function. 

What do you think?

**Comment by mdietze** [comment]
Sounds good

**Comment by ryankelly-uiuc** [comment]
OK, @mdietze , this seems to be working well. All sensitivity and ensemble analysis stuff gets saved to directories named by ensemble ID, with variable and years in filenames where needed to uniqueify. It's a little more complicated then necessary to try to preserve backwards compatibility and allow future flexibility. Should work with existing workflow.R, but also allows passing variable/year/ensemble.id directly to functions to re-run analyses on existing ensembles, or run new ones with different variables or years.

**Pull request merged**
