### PR TITLE
fixes-GH-#1869-site.id-removed

### PR DESCRIPTION
**Pull request by rahul799**
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ x] When possible
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dlebauer** [comment]
@rahul799 thanksFor the contribution but it looks like only the .Rd and not the .R files were edited. Based on a quick look at https://github.com/PecanProject/pecan/issues/1869 I think that the fix will require editing the function definitions and roxygen documentation in the corresponding .R files. Then the .Rd files will be automatically generated

**Comment by infotroph** [comment]
Expanding on @dlebauer's comment: Rd files are rebuilt "automatically" in the sense that it's part of what happens when you run `make` on your machine before pushing, but unfortunately we don't (yet) have any machinery in place to update Rd files on the server side. If we had that, this process would be quite a bit easier for everyone but especially for new contributors.

@rahul799 Have you already found our [developer guide](https://pecanproject.github.io/pecan-documentation/develop/developer-guide.html#developer-testing-integration)? Unfortunately the details on our build process are kind of scattered around, but see:
* The section titled  "Recommended Workflow: A new branch for each change" in the [Git chapter](https://pecanproject.github.io/pecan-documentation/develop/developer-guide.html#using-git). Much of this will look very basic to you because it's written for people who are new to Git, but it's a good overview of our workflow.
* The [continuous integration](https://pecanproject.github.io/pecan-documentation/develop/developer-guide.html#continuous-integration) section for an overview of what happens after you push (and why Travis fails so often :( )

**Comment by rahul799** [comment]
@infotroph I saw your comment after pushing the [commit](https://github.com/PecanProject/pecan/pull/2500/commits/dfdb34e7186be55324bd6ab45af1feeb0b34cc6a), but yes I ran the .R files by `roxygen2` package in my local system to generate the new .rd files.I ran it for  **download.CRUNCEP_Global.R**

 only & saw very minor changes in corresponding .rd. So I didn't run it for all but I don't think, there would be any changes in the .rd files other than my last [commit](https://github.com/PecanProject/pecan/pull/2500/commits/e459c773c94bef755ec2ee88f7e178cbe4cb7243).

@infotroph @dlebauer  Please have a look at it & let me know If you want any changes. Meanwhile I will go through the` developer guide` also.

**Comment by rahul799** [comment]
@infotroph I also found `site_id` in few packages like **extract_local_CMIPS.R** where it is taken as an argument but there is no use of it in the file. So, is it useful in here or should we remove it?

**Comment by infotroph** [comment]
>  I also found site_id in few packages like extract_local_CMIPS.R where it is taken as an argument but there is no use of it in the file. So, is it useful in here or should we remove it?

@rahul799 Yes, those should also be removed and the process will be similar to the download functions, but I'd recommend doing them in a separate PR to keep this one from getting ungainly.  Feel free to open an issue for it to keep track in the meantime.

**Comment by mdietze** [comment]
@rahul799 I'm catching up on PR and wanted to confirm my interpretation that this PR can be closed because it was superseded by 2502

**Comment by infotroph** [comment]
@mdietze @rahul799 Looks like there was partial overlap between this and #2502, but at least GLDAS, MACA, and MsTIMIP aren't touched there. I think the original intention was for one to be fixing the download functions and the other to fix the extraction functions, then the scope drifted as we played CI whac-a-mole.

**Comment by rahul799** [comment]
@mdietze , I completely agree with the @infotroph .

**Comment by mdietze** [comment]
Ok, so if some of this still needs to go in then the conflicts need to be resolved. Thanks

**Comment by mdietze** [comment]
@rahul799 just a reminder that this PR has been open for a good while with some merge conflicts that need to be resolved

**Comment by rahul799** [comment]
I am closing this PR as many changes are addressed in other PR.

**Pull request closed without merging**
