### PR TITLE
Fix create site performance issue 02 file

### PR DESCRIPTION
**Pull request by ch1eroe1**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

### CODE REVIEW

**Comment by tonygardella** [comment]
@robkooper Do you have time to review this?

**Comment by mdietze** [comment]
@robkooper just wanted to make sure that either fixing this PR or closing it is still on your TO-DO at some point (not urgent, but the PR has been open since Feb)

**Comment by robkooper** [comment]
still planning on doing this, has slipped down on my radar.

**Comment by mdietze** [comment]
@robkooper still waiting for fixes here

**Comment by tonygardella** [comment]
@robkooper Pinging you to take a look at this

**Comment by tonygardella** [comment]
@robkooper Can you take a look at this?

**Comment by robkooper** [comment]
This will be superseded by #2105

**Pull request closed without merging**
