### PR TITLE
Template and history file for the latest git version of ED2

### PR DESCRIPTION
**Pull request by Viskari**
As the title says, this contains the two files needed to run the latest git version of ED2 through PEcAn. Just as a note, the file names are not git, but rgit, because the pecan assumes that in front of the given version number.

### CODE REVIEW

**Comment by mdietze** [comment]
@Viskari this commit includes all your DART FIA assimilation work. Could you submit a pull request for just 5831b47

**Comment by Viskari** [comment]
I've been trying to figure out how to do that. I closed the previous pull
request and tried to include only how that in the current pull request. How
do I only specify that part in the pull request.

**Comment by mdietze** [comment]
Probably easiest would be to create a new branch that's a clean version of the mainline master and then use the git cherry-pick to pull over just the individual commits. You can then push that branch to github and do a pull request from that branch to the mainline

**Comment by apourmok** [comment]
The other way is to use gitlog to find out which commit has your DART FIA assimilation work, revert to that one by the commit number, push again and then do another commit/push with your bugfix. I followed the instruction below and it was really helpful:
http://samwize.com/2014/01/15/how-to-remove-a-commit-that-is-already-pushed-to-github/

**Comment by mdietze** [comment]
Yes, but in doing a revert you would loose all the changes in between. I don't think we want to loose previous commits but rather just pick out specific commits (which is what cherry-pick is designed to do)

**Comment by apourmok** [comment]
You are right, I did not mean "git revert" and meant reverting the push. I do it like this:
git reset "commit number" --hard
git push origin -f

**Pull request closed without merging**
