### PR TITLE
Met Temporal Downscaling Fixes & Updates

### PR DESCRIPTION
**Pull request by crollinson**
## Description

Major changes: 
1) Critical: Fix precipitation redistribution bug (tdm_lm_ensemble_sims.R line 572 most critical); 
2) Improve support for single-prediction downscaling by using the model coefficients and circumventing creating/pulling from a simulated posterior distribution of coefficients (necessary for generating an ensemble that characterizies and propagates uncertiainty)

## Motivation and Context
For the precipitation redistribution issue: there was an issue where precipitation after temporal downscaling was consistent and sometimes dramatically less than at the outset.  Turns out this was due to a really stupid mistake that wasn't caught long ago.

For the single-prediction feature: the original motivator of the TDM code was to generate an met ensemble that could be used to calculate driver uncertainty and uncertainty associated with spatial and temporal downscaling processes.  Turns out a lot of applications (including my own) don't really need this.  The previous work-around was to generate a small ensemble and take the mean.  But this lead to failed sanity checks and drivers that couldn't be executed in ED.  [insert call fail_whale] The new workaround is faster and more robust since it uses the mean generated during the model fitting stage rather than the simulated distribution of model coeffecients.

## Review Time Estimate

- [X] Immediately --> the precip bug is essential if anybody is currently using this routine
- [ ] Within one week
- [ ] When possible
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)  [I don't know if there was an issue; this is a long-overdue PR]
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by ankurdesai — APPROVED** [review]
This seems like a good fix and taking mean makes sense if ens=1. Code looks ok to me.

**Comment by mdietze** [comment]
@crollinson build is currently failing because you need to have roxygen rebuild the package documentation

**Comment by crollinson** [comment]
@mdietze Can you or someone in the team remind me how to do that or where the instructions for that are?

**Comment by crollinson** [comment]
or if there's someway someone can help me build the documentation -- I tried going to the data.atmosphere directory and running roxygen2::roxygenise(), but am running into all kinds of dependency errors because I don't have the full Pecan environment installed as a package.  (Never figured out how to do that.)

**Comment by mdietze** [comment]
Grabbed a copy of your branch and seeing if I can get it working...

**Comment by robkooper** [comment]
@crollinson what I tend to do is:

```
docker pull pecan/base:develop
docker run -ti --rm -v ${PWD}:/pecan pecan/base:develop bash
cd /pecan
```

now you can do everything there is a fairly new version, you can type make in there to build it, etc.

**Pull request merged**
