### PR TITLE
Fixed Decadal time range input Bug in download.GFDL 

### PR DESCRIPTION
**Pull request by jsimkins2**
Slicing was occuring in wrong part of the loop so fixed that. Also, param arguments weren't named properly so I edited those in download.GFDL and met.process

### CODE REVIEW

**Comment by mdietze** [comment]
Pull request has conflicts that need to be resolved. You don't need to close the PR, you just need to pull the latest code from upstream, resolve conflicts, and push the changes.

**Comment by jsimkins2** [comment]
Not sure why the branch still has conflicts...
git fetch --all
git reset --hard origin/master
git pull upstream master

Do I need to unstage these commits and then pull?

**Comment by mdietze** [comment]
You should end up with files that have conflicts in them. You need to resolve those conflicts **by hand** and then commit the files.

**Comment by jsimkins2** [comment]
No more conflicts, but I want to test it out real quick before you accept the pull @mdietze

**Comment by jsimkins2** [comment]
@mdietze Good to go!

**Pull request merged**
