### PR TITLE
GFDL hacks added to Met Process

### PR DESCRIPTION
**Pull request by jsimkins2**
Cleaned up download.GFDL function and added default arguments for GFDL model/experiment/scenario (let me know if I need to rerun roxygen and such with the edits) and added GFDL hacks to met.process. Able to run jobs successfully in PEcAn with changes to met.process

### CODE REVIEW

**Comment by mdietze** [comment]
Code looks fine, but Github says they're conflicts. If you pull from the mainline, resolve those conflicts, and push back up I should be able to accept this quickly

**Comment by ankurdesai** [comment]
My guess is since we both edited met process at same time, you'll need to move your met process version temporarily elsewhere, pull in the mainline master and put back in the changes you made on top of the met process I edited for CSV. 

Ankur Desai, UW-Madison
 +1-608-218-4208 [mobile]

**Comment by robkooper** [comment]
use git pull origin/master and look at the conflicts, don't copy and paster since that will most likely result in things getting lost. Where there are conflicts you will find <<<<< and >>>> in your code, just fix those sections.

**Comment by jsimkins2** [comment]
Ok, I'm up to date now, I'm just going to add my updates to Ankur's met.process

**Comment by jsimkins2** [comment]
Tried integrating changes, now getting an error on line 353 of met.process. Here is the workflow.Rout

Warning in postgresqlQuickSQL(conn, statement, ...) : 
Could not create executeSELECT * from dbfiles where id = 
2016-07-01 13:09:52 SEVERE [db.query] : 
Error executing db query 'SELECT * from dbfiles where id = ' errorcode=0 
message='ERROR: syntax error at end of input LINE 1: SELECT * from 
dbfiles where id = ^ '

**Comment by mdietze** [comment]
It looks like it's not getting a dbfile ID somewhere

**Comment by jsimkins2** [comment]
It will run for the year 2004 oddly enough. But any other year, here is the traceback;

Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at end of input
LINE 1: SELECT * from dbfiles where id = 
                                         ^
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create executeSELECT * from dbfiles where id = 
2016-07-01 16:32:04 SEVERE [db.query] : 
   Error executing db query 'SELECT * from dbfiles where id = ' errorcode=0 
   message='ERROR: syntax error at end of input LINE 1: SELECT * from 
   dbfiles where id = ^ ' 


Any ideas on how to fix this?

**Comment by mdietze** [comment]
Is this rerunning the same site for a new year?  If so that's a known bug and we're good. If only 2004 works at any site then this is a new bug

**Comment by ankurdesai** [comment]
Its possible it has something to do with database entires getting messed up from testing met.process by both of us. Look at the “inputs” and “files” table toward the end and see if things don’t make sense. Greetings from a houseboat on lake union, seattle!  -ankur

**Comment by jsimkins2** [comment]
@mdietze It was the known bug. Just ran different years at different sites and it ran successfully!

**Pull request merged**
