### PR TITLE
Quick "fix" to stop printing during write.configs.FATES

### PR DESCRIPTION
**Pull request by serbinsh**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
Will need to resolve conflicts. Might also want to set some of them to logger.debug rather than deleted or commented out -- that way they won't show up in the logs most of the time but you can easily turn them on

**Comment by serbinsh** [comment]
Trying to sort out / find the conflicts.  Are you saying we should keep those print statments but just change to logger.debug()?

**Comment by serbinsh** [comment]
@mdietze Oh yes I see.  Want me to switch to logger.debug(dim(trait.values)), logger.debug(npft), etc, etc?

**Comment by mdietze** [comment]
wouldn't hurt to keep some of them as logger.debug to help with debugging. e.g. I could envision dumping the pfts, parameters, etc as useful to debugging

**Comment by serbinsh** [comment]
Cool

**Pull request merged**
