### PR TITLE
Major documentation restructuring

### PR DESCRIPTION
**Pull request by ashiklom**
## Description

- All `Rmd` files in the `book_source` directory and subdirectories are used (in numerical-alphabetical order). There is no longer a need to maintain a list of files to build in the `_bookdown.yml` file. One disadvantage of this is that files not in `book_source` won't be built by default, so if we want to include other files, the most straightforward way is to use symbolic links.
- The file naming and folder structure of the documentation has been revised to mirror the structure of the documentation (it has to, because the Rmd files are pulled in in numerical order). We've also tried to make the directory structure more consistent (e.g. subdirectory level matches header level).
- We've revised the outline of the documentation itself. There are now the following major sections:
  - Introduction (welcome page, code of conduct, about the docs)
  - Basic user guide -- the basic web interface
  - Intermediate user guide -- the PEcAn XML and advanced features of the web interface
  - Advanced user guide -- the PEcAn workflow script and associated functions; extending PEcAn with new models and data; the PEcAn modules (RTM, allometry, photosynthesis, etc.)
  - Developer guide -- Setup and maintenance; Git; coding practices and style; directory structure
  - Reference -- PEcAn standards; lists of models, products and data sources; etc.

Note that this is a work in progress. The main goal here was to establish a framework for the documentation that would make it easier to identify and fill in missing documentation, and make it clearer where new documentation should go and how it relates to the existing documentation.

## Motivation and Context

We've been discussing documentation overhauls for a while. This is our attempt.

## Review Time Estimate

- [ ] Immediately
- [X] Within one week
- [ ] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [X] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ashiklom** [comment]
@mdietze @tonygardella Looks like the problem with the build is it's not finding the `GITHUB_PAT` variable. Not totally sure how to fix that.

https://travis-ci.org/PecanProject/pecan/builds/335715004#L7549

**Comment by tonygardella** [comment]
Odd, GITHUB_PAT it is defined in our TRAVIS settings. I try and see if anyone else has this issues, otherwise I'll just delete and create a new token.

**Comment by tonygardella** [comment]
Created a new GITHUB_PAT.

**Comment by tonygardella** [comment]
Looks like GITHUB_PAT wasn't the only issue. If you look at the [repository](https://github.com/PecanProject/pecan-documentation) TRAVIS pushes to, it has only been rendering the html tutorial files. For some reason it's skipping the files in book_source.

**Comment by ashiklom** [comment]
It's skipping the files because it still can't find the `GITHUB_PAT` variable: https://travis-ci.org/PecanProject/pecan/jobs/335770778#L7582

Are there security settings that only expose the Travis secret variables to certain branches?

**Comment by ashiklom** [comment]
@tonygardella @mdietze Travis docs have this to say about environment variables ([source](https://docs.travis-ci.com/user/environment-variables/)):

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

So it makes sense why the documentation isn't being built for PRs. (Also, we explicitly skip documentation building for PRs anyway).

The reason the documentation hasn't been updated for a while is that there's an error in the documentation build that for some reason wasn't captured by `Rscript` (for instance, see line 7610 of this recent build of `develop` -- https://travis-ci.org/PecanProject/pecan/builds/334641325#L7610). I'll need to figure out how to actually catch that error, but in the meantime, these docs should build because I have tested `make` many times locally and can confirm the documentation compiles.

**Pull request merged**
