### PR TITLE
Release/v1.5.3

### LINKED ISSUE #1886: NA in VPD makes metgapfill fail.
@ankur In metgapfill, I'm getting an error: 
```
Error in VPD[VPD > es] <- es : NAs are not allowed in subscripted assignments
```  
and then it exits met.process. Looking at VPD there are 11 values in a row that are NA.  

## Context
I was doing a run at Niwot Ridge from 2003-2006 using Ameriflux and the error shows up when processing 2005.

## Possible Implementation
For solutions should I tell the user to select new dates and tell which date is problematic, or should there be fix to the code to somehow bypass the NAs?

### PR DESCRIPTION
**Pull request by ankurdesai**
Not sure I'm doing this right. Following Tony's instructions to move my commit to close #1886 from develop to 1.5.3.

### CODE REVIEW

**Comment by mdietze** [comment]
@ankurdesai this PR seems to just be moving the contents of PecanProject:release/v1.5.3 into develop via your personal branch, but without the fixes discussed in #1889. Because it's not different from release Github won't let me change the branch the PR is going into. However, when I try to change #1889 to pull into release instead of develop, then there are >100 changes rather than just the one. So... I think you need to manually apply the changes you did in #1189 into this branch, then commit and push, after which point we should be able to change the PR to be into release and be done.

**Comment by ankurdesai** [comment]
That's what I thought I did, but I'll try again.

**Comment by tonygardella** [comment]
@ankurdesai I changed the base and it looks like everything is fine now.

**Comment by ankurdesai** [comment]
Thanks. I think it's ready now.

**Pull request merged**
