### PR TITLE
Style cleanup for `modules/rtm/R/*.R` scripts 

### PR DESCRIPTION
**Pull request by bpbond**
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Substituted `seq_len`, `seq_along`, and `paste0`, and `file.path` as necessary. Made sure all functions end with an explicit `return`.

### CODE REVIEW

**Comment by bpbond** [comment]
Not sure what is going on here. The travis log shows the `PEcAn.utils` installation failing (lines 4300-) because ggplot2 is required but not available. I don't think any of my `rtm` changes could have borked this.

**Comment by mdietze** [comment]
@bpbond could you try a merge and conflict resolve on this PR?  I'd like to see if the changes you and @ashiklom have made to Travis, make, and package dependencies might have resolved the quirky errors this build was getting

**Comment by bpbond** [comment]
@mdietze will do. Some gnarly conflicts, but should figure things out in a bit.

**Comment by bpbond** [comment]
Checks passed!  🎉

**Comment by mdietze** [comment]
quickly merged before something else caused another conflict...

**Pull request merged**
