### PR TITLE
MsTMIP_NARR Function

### PR DESCRIPTION
**Pull request by jsimkins2**
MsTMIP_NARR function code complete and working

Added precipitation conversion (from mm/6hr to kg/m2/s) to download.CRUNCEP

### CODE REVIEW

**Comment by mdietze** [comment]
What does this file do? modules/data.atmosphere/inst/scripts/download.CRUNCEP_Global.R

It looks like it's basically a copy of the version in modules/data.atmosphere/R, but since it's in inst/scripts it will never get called.

Oh, and I think you'll need to run Roxygen for this package so that it can add your new function to the export and generate its man page.

**Comment by jsimkins2** [comment]
@mdietze I moved the file from inst/scripts to data.atmosphere/R and forgot to delete the inst/scripts one. I just deleted it and keyed 'git add' so will that automatically update this pull request? Also, I do need to run Roxygen, completely forgot. Is there documentation for this on Pecan github? Is there anything else I need to do for this function besides run Roxygen?

**Comment by mdietze** [comment]
James, in addition to the git add you need to do a git commit and git push for the pull request to update (but once you've pushed the code to the web you don't have to do anything on the web to update the pull request).

The easiest way to run Roxygen for the _whole_ of PEcAn is to run the build script with the --documentation flag (i.e. scripts/build.sh --documentation). To update the docs on just this one package then within R you load the Roxygen2 library and use the roxygenise() function.

After you update the documentation you'll need to add, commit, and push the files that have been added or changed.  git status will show you which ones these are.

**Comment by jsimkins2** [comment]
@mdietze Thanks for the instruction. I think I accomplished all of them. However, I'm unsure about the deletion of download.CRUNCEP from the inst/scripts folder. I removed it from my local pecan, git committed and pushed it, and now it doesn't show up on my fork of pecan, but is still showing up on the pull request from my end. Is there a delay before the pull request will update my fork's version?

**Comment by mdietze** [comment]
I still see download.CRUNCEP in your code that's on github, so it's not just the pull request but also the push that still has it. Did you use the git rm command or did you just manually delete the file? If the latter then that would explain why you don't see the file but it's still in your repository.

**Comment by jsimkins2** [comment]
@mdietze that would explain it, thanks!

**Pull request merged**
