### PR TITLE
Fixing halton

### LINKED ISSUE #730: method="halton" is harcoded in the workflow
Right now sampling method halton is hardcoded in the workflow

```
run.write.configs(settings, write=settings$database$bety$write, ens.sample.method="halton")
```

We should be able to choose a sampler from settings.

### PR DESCRIPTION
**Pull request by istfer**
Closes #730 

I made the changes for passing the sampling method from settings to downstream code. Right now only halton sequence and uniform sampling is implemented.

Shall we migrate get.ensemble.samples function to uncertainty module (where get.parameter.samples are)?

### CODE REVIEW

**Comment by mdietze** [comment]
I'm in favor of migrating get.ensemble.samples since it makes sense conceptually for this to be in the uncertainty module. @dlebauer are you aware of anything that move might break?

**Comment by jam2767** [comment]
Woohoo for being helpful! Looks good now. @mdietze I think this commit can be accepted.

**Comment by mdietze** [comment]
Sorry for not seeing this earlier, but I'm going to respectfully disagree with @jam2767's suggestions and and ask that some of the last commit be reverted. Josh, what you're referring to as 'hard coded' is just the setting of a default, which is completely fair, valid, and indeed desirable for cases where there's a sensible or preferred option that we want to nudge most users to use. What @istfer was correct in catching, however, is that if no value is supplied in the settings, but the arguement is still being set by the settings, that the default value will be explicitly overwritten by a NULL, causing a crash. A simpler and more clear fix than handling this in the **if** block would be one line at the top that sets the variable to a sensible default if NULL is provided (I no longer thing that default should be halton -- probably random instead). 

While we're at it, could you also change the name of the variable halton.samples, which is becoming an increasingly misleading variable name if there are a lot of non-halton sampling alternatives.

**Comment by istfer** [comment]
OK, I put back the default function arguments, but as "uniform" this time and changed the variable name. Also set the default to uniform random sampling as @mdietze suggested if user provides no method in the settings.

**Comment by jam2767** [comment]
@istfer sorry for confusing the default argument with "hard coding". Sounds like it is good to go now though!

**Comment by istfer** [comment]
@jam2767 no problem at all, it still helped with the other thing!

**Pull request merged**
