### PR TITLE
db pool was throwing errors

### PR DESCRIPTION
**Pull request by robkooper**
the pool created errors, will investigate later, this should fix the issue.

I think the pool does not play nice with some of the queries we have and dplyr queries we have. Right now this seems to make it work correctly.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by robkooper** [comment]
did not create changelog entry since API was introduced in this release.

**Comment by ashiklom** [comment]
Can you provide more context on the errors? The reason I created the pool was because without it, the API would start to choke if you submitted even a relatively small number of queries at a time.

**Review by mdietze — APPROVED** [review]

**Comment by ashiklom** [comment]
We should definitely revisit this. I introduced the connection pool because the API DB connection would choke under even relatively light strain. Otherwise, I'd never encountered any errors with submitting jobs through the API with the DB pool enabled. I wish we could have seen more on the error before merging this.

**Comment by robkooper** [comment]
I agree, I like the idea of the pool. Problem was that when I was testing the code it would fail to get the basic /api/info endpoint.

**Pull request merged**
