### PR TITLE
Replaced `testthat` function

### LINKED ISSUE #2987: Don't use `testthat` inside of functions
### Bug Description

The `testthat` package is made for unit testing, not use inside of functions.  `testhat` functions appear in at least a couple of places:
- `check_ed_metheader()`
- `check_ed_metfile()`

These should be replaced with calls to `stopifnot()` or something from the `assert` or `assertthat` packages

### PR DESCRIPTION
**Pull request by meetagrawal09**
## Description
The PR tries to remove use of `testthat` outside of unit tests and replace it with `assertthat`
This PR does not replicate efforts made in #3067 
PR tries to fix #2987 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [X] When possible

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by meetagrawal09** [comment]
> I don't know. In RStudio you can use "Find in files ..." in the Edit menu to search for `testthat` or maybe `expect_`

Followed this. There are no other places which need to be updated.

**Comment by meetagrawal09** [comment]
Can you guide me what further changes need to be made ( or commands need to be run ) in-order to make the checks pass and if the change made to this function seems correct ?

**Comment by Aariq** [comment]
I think maybe you need to run this script: https://github.com/PecanProject/pecan/blob/develop/scripts/generate_dependencies.R

**Comment by meetagrawal09** [comment]
This PR covers all the instances of `testthat` being used outside of unit testing which have not already been a part of #3067 
The work on this PR is complete and it is ready for a review

**Review by mdietze — APPROVED** [review]

**Pull request merged**
