### PR TITLE
Neon initial soil carbon fraction calculation

### PR DESCRIPTION
**Pull request by Qianyuxuan**
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DongchenZ** [comment]
The code is outdated, @Qianyuxuan you probably need to do a git pull from PEcAn develop branch and then update the code accordingly.

**Comment by dlebauer** [comment]
@Qianyuxuan key step is to resolve this conflict https://github.com/PecanProject/pecan/pull/3059/conflicts

**Review by dlebauer — CHANGES_REQUESTED** [review]
please replace `select(df, .data$colname)` with `select(df, "colname")` as of #3055

**Comment by mdietze** [comment]
@Qianyuxuan please respond to the issues your collaborators have raised in place, rather than deleting this branch and opening a second, virtually identical PR. The PR review process does not function if your collaborators cannot see what has changed from version to version and how you have responded.

**Review by mdietze — APPROVED** [review]

**Comment by mdietze** [comment]
@dlebauer looks like @Qianyuxuan responded to your change request. Could you confirm and "approve" so this can be merged?

**Comment by Qianyuxuan** [comment]
>

**Comment by Qianyuxuan** [comment]
> @Qianyuxuan key step is to resolve this conflict https://github.com/PecanProject/pecan/pull/3059/conflicts

The conflict was resolved.

**Comment by Qianyuxuan** [comment]
@mdietze Hi Mike, just to let you know I have resolved the conflict. Please let me know if there are other issues.

**Review by mdietze — APPROVED** [review]

**Pull request merged**
