### PR TITLE
Minor edits to documentation for adding a model

### PR DESCRIPTION
**Pull request by KristinaRiemer**
Added/rearranged text and added some screenshots to the [Adding An Ecosystem Model section](https://pecanproject.github.io/pecan-documentation/develop/adding-to-pecan.html#adding-model) in the PEcAn book. 

## Description

* Added verbs to most section headers (e.g., **PFTs** changed to **Add Plant Functional Types**)
* Tried to split all sections up into paragraphs describing why something needs to be done and then how to do it 
* Included screenshots of how to do most steps in BETY

## Motivation and Context

While generating priors for new PFTs, I found that the instructions could be more clear and that pictures of what to do would be helpful. 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
Tagging @bailsofhay in this because we're paired up for code review this week.

**Comment by KristinaRiemer** [comment]
@robkooper let me know if I didn't do that right.

**Comment by KristinaRiemer** [comment]
@robkooper does this look okay now?

**Comment by mdietze** [comment]
@KristinaRiemer there's now some merge conflicts on this PR. Can you reconcile them so we can get this in?

**Comment by KristinaRiemer** [comment]
Closing this in favor of #2521

**Pull request closed without merging**
