### PR TITLE
[Docs] Fix chunk rendering in dependencies appendix

### PR DESCRIPTION
**Pull request by infotroph**
## Description

Fixed two code chunks that Rmarkdown was evaluating instead of displaying

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
I've never seen the \```r syntax, how is that different from just a generic code block \``` ?

**Comment by infotroph** [comment]
@mdietze Loosely, ` ```r ` is a generic Markdown convention for "This is some preformatted text, please render it in a fixed-width font and apply syntax highlighting that assumes it's R code", while ` ```{r [options]} ` is Rmarkdown notation for "This is a chunk of R code, please interpret it and display the results in a way further specified by [options]"

**Comment by mdietze** [comment]
So it sounds like  \``` is a non-evaluated code block, and \```r is a non-evaluated code block that also has R syntax highlighting?  Good to know

**Comment by infotroph** [comment]
@mdietze Yep, correct. The quality of the highlighting you get will vary wildly between platforms 🙈 , but it does often come in handy

**Pull request merged**
