### PR TITLE
Updating fia2ED.R

### PR DESCRIPTION
**Pull request by apourmok**
Updated fia2ED.R script to comply with Ryan Kelly's changes to FIA DB, changed all query to lower cases and created indexes. Query analyze report shows the speed is the same and first pass in extracting worked. Will do more thorough analyze next week.

### CODE REVIEW

**Comment by mdietze** [comment]
There's a bunch of stuff in this pull request other than you fia2ed fixes -- where's the rest of this coming from?

**Comment by apourmok** [comment]
@mdietze fixed them and now you should be able to approve this to main line.

**Comment by mdietze** [comment]
Ok, now you've got a bunch of different files that are not part of your bug fix. Many of them appear to come from the RTM package and end in ~HEAD which implies there's a lot of conflicts in one of your merges

**Comment by apourmok** [comment]
I thought I removed all of them yesterday but will clean it up again today.

On Tue, Mar 31, 2015 at 10:32 AM, Michael Dietze <notifications@github.com>
wrote:

> Ok, now you've got a bunch of different files that are not part of your
> bug fix. Many of them appear to come from the RTM package and end in ~HEAD
> which implies there's a lot of conflicts in one of your merges
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PecanProject/pecan/pull/402#issuecomment-88111343>.
>



-- 
Afshin Pourmokhtarian, Ph.D.
Postdoctoral Research Associate
Dietze Ecological Forecasting Lab
Boston University
Deptartment of Earth & Environment, Rm 130
685 Commonwealth Avenue
Boston, MA 02215

**Pull request merged**
