### PR TITLE
Last few tweaks to PEcAn.utils

### PR DESCRIPTION
**Pull request by moki1202**

### CODE REVIEW

**Comment by infotroph** [comment]
When merged, this will close #2856

**Review by mdietze — APPROVED** [review]

**Comment by mdietze** [comment]
@moki1202 @infotroph this all makes sense and appears to build fine. Is there more coming or should "draft" be removed so we can pull this in?

**Comment by infotroph** [comment]
@mdietze Changelog update stil incoming. @moki1202 will you mark this ready for review when you push that?

**Comment by infotroph** [comment]
Changelog is in #2859 -- OK to pull this in now.

**Pull request merged**
