### PR TITLE
Make sure not to overwrite previously set on.exit actions

### PR DESCRIPTION
**Pull request by infotroph**
## Description
Following up on one of @robkooper's comments on #2483 before I forget about it

## Motivation and Context
IMO the default `on.exit` behavior (of replacing any actions scheduled earlier in the function rather than adding to them) is backwards and for defensive programming we should usually call it with `add = TRUE` unless the situation specifically requires `add = FALSE`

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mdietze** [comment]
`on.exit` is used a lot of other places in PEcAn -- do we want to fix them all at once since it's on our minds.

**Comment by infotroph** [comment]
@mdietze That would be smart, but will need a little bit of care to make sure we don't clobber any places add=FALSE *was* intended. If you're OK leaving this open for a while I can try to work through the other packages and slowly add them in.

**Comment by mdietze** [comment]
From previous discussions when we wrote those other sections, I don't think any of us were aware that add=FALSE was the default and having done a quick search I can't think of any example where we'd deliberately want to clobber that on.exit stack, as it would just lead to errors and leaks.

**Comment by infotroph** [comment]
Don't merge yet; More commits coming soon.

**Comment by infotroph** [comment]
@robkooper @mdietze this is ready for another look

**Pull request merged**
