### PR TITLE
added ameriflux vignette refs #404

### PR DESCRIPTION
**Pull request by dlebauer**
@bcow @jam2767 

regarding the documentation suggested in #404, this vignette provides an example of how to use `download.Ameriflux` and `met2cf.Ameriflux`. Would be great to have similar examples for other functions. It's really just an annotated script of a use of these functions (e.g. I created this because I found it useful for a separate analysis).

### CODE REVIEW

**Comment by mdietze** [comment]
I have mixed feelings about this vignette and the value of creating similar vignettes for the other met2CF functions. While these met functions can obviously be called on their own, they were designed to work as internal functions within met.process. I worry that this sends the wrong message about that usage and wonder if a more general Vignette about how to call met.process might be more appropriate.  

If this is retained then I'd argue that on the last step you should use met2model.BioCro rather than a function that's called internally by met2model.BioCro since this would make it more clear about how to alter this script to call other model met functions

**Comment by dlebauer** [comment]
I think exposing such functions makes them more useable, indeed one of the design principles of PEcAn (and modern software more generally) is to develop tools that are powerful at the high level but also provide modular, reusable bits of code. The goal of this vignette is to demonstrate how these functions can be used (they are exported, after all).

The met.process is useful in the overall PEcAn workflow, but it isn't a general, lightweight utility like the lower level functions. Based on the documentation, it requires PEcAn.DB, PEcAn.settings, an instance of BETYdb, and a settings file. In addition, it only works for downloading NARR and Ameriflux - I have lots of met data that it does not currently work on.

I also think that knowing what is going on internally is important, as is demonstrating to others, including other developers (each other), the tools that we are creating.

**Comment by mdietze** [comment]
Ok, so it sounds like you agree we should have a more general vignette that covers met.process and all the conversion functions in one place, rather than an Ameriflux-specific vignette, so we can hold off on  (or rename) this specific vignette.

"In addition, it only works for downloading NARR and Ameriflux - I have lots of met data that it does not currently work on"
Then we'd really appreciate it if you could set up download.[source] and met2CF.[source] functions for these other met data so that they can be called within met.process as well. NARR and Ameriflux are just the test cases that Betsy's started with, not the objective of the workflow.

**Comment by dlebauer** [comment]
> Ok, so it sounds like you agree we should have a more general vignette that covers met.process and all the conversion functions in one place, rather than an Ameriflux-specific vignette, 

Yes I agree with this.

I'd suggest that such a general vignette could combine a few of the vignettes that I have previously written such as:

* met2CF.csv 
  * [Tully, NY](https://github.com/ebimodeling/willow_da/blob/master/vignettes/convert_met2CF.Rmd) 
  * [SoyFACE example](http://rpubs.com/dlebauer/soyface_met_2010).
* [Comparison of NARR, NCEP, MsTMIP-NARR, and EBI Farm station data](https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/vignettes/compare_narr_cruncep_met.Rmd) ... (see published version with graphs rpubs here]


> so we can hold off on (or rename) this specific vignette.

I don't think that this follows: why not rename this vignette to something more general _after_ it has been generalized?

> we'd really appreciate it if you could set up download.[source] and met2CF.[source] functions for these other met data.

I am happy to do so for the datasets that I already have (NCEP, MsTMIP drivers from NARR and CruNCEP, ISIMIP-CMIP5 ensembles). The main thing I need is a place to put the files that is a) large enough and b) where people can access them. (I can chat with @robkooper about the best way to do this). This should be opened as a separate issue.

**Comment by mdietze** [comment]
@dlebauer I view the issue of committing the code to allow PEcAn to interact with NCEP, MsTMIP, ISIMIP, etc as completely separate from where to deposit that data -- the latter is dynamic and just a matter of making the appropriate Inputs and dbfiles records. Creating new issues for these functions would be great.

**Comment by dlebauer** [comment]
> committing the code to allow PEcAn to interact with NCEP, MsTMIP, ISIMIP, etc as completely separate from where to deposit that data

I wasn't referring to where to deposit the data, but where to put the data so that PEcAn can retrieve it.

**Comment by mdietze** [comment]
I'm missing the distinction between "deposit data" and "put data" or why it matters. The data just needs to be in a directory with read permissions that's registered with the database. Since its registered with the database, this has no impact on how the met2CF and download functions are written or on anyone else who might use them outside your own server. Please create issues for these functions so we can move this discussion there.

**Comment by dlebauer** [comment]
opened #461

**Pull request merged**
