### PR TITLE
fix for tidyselect 1.2.0

### PR DESCRIPTION
**Pull request by Aariq**
## Description

replaces `select(df, .data$colname)` with `select(df, "colname")` and other related changes.

## Motivation and Context

Use of `.data` in tidyselect situations (e.g. `select()`, `rename()`) is deprecated in tidyselect 1.2.0: https://www.tidyverse.org/blog/2022/10/tidyselect-1-2-0/

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by dlebauer — APPROVED** [review]

**Comment by infotroph** [comment]
Is support for selecting via quoted string a recent addition that means we should specify a minimum dplyr version? Or has it been around for a while and I just didn't notice because mutate is different?

Either way, hurray for decrufting!

**Comment by Aariq** [comment]
> Is support for selecting via quoted string a recent addition that means we should specify a minimum dplyr version? Or has it been around for a while and I just didn't notice because mutate is different?
> 
> Either way, hurray for decrufting!

Looks like it's been around since 2017 when `dplyr` started using `tidyselect` (https://dplyr.tidyverse.org/news/index.html#major-changes-0-7-5)

**Comment by infotroph** [comment]
> Looks like it's been around since 2017 

Cool, then I see no need to add any version specifiers

**Review by dlebauer — CHANGES_REQUESTED** [review]
could you please update https://github.com/PecanProject/pecan/blob/develop/book_source/02_demos_tutorials_workflows/05_developer_workflows/03_coding_practices/01-coding-style.Rmd?

**Review by dlebauer — APPROVED** [review]

**Pull request merged**
