### PR TITLE
trigger a workflow from document/style

### PR DESCRIPTION
**Pull request by robkooper**
Should trigger a build after the document or style actions.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [X] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mdietze — APPROVED** [review]

**Comment by robkooper** [comment]
closing this PR, since I had to merge it into develop to test.

**Pull request closed without merging**
