### PR TITLE
download and met2CF functions for Clowder

### PR DESCRIPTION
**Pull request by infotroph**
## Description
This is an R translation of the Clowder/Geostreams import proposed in #1268. It provides two new functions in data.atmosphere: `download.geostreams` looks up datasets by site name and date range and saves the results as JSON, then `met2cf.geostreams` converts that JSON to CF met format.

Please do not merge yet -- still testing, but design/implementation critiques requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ankurdesai** [comment]
@infotroph Can you provide a small vignette or example? Could try to test.

**Comment by infotroph** [comment]
@ankurdesai Word is that the API is still in beta and isn't issuing keys yet, but if you're willing you can try it with password auth:


* Open https://terraref.ncsa.illinois.edu/clowder/ in a browser, click "sign up", follow instructions to pick a password
* wait for an email confirmation link (I'm not clear if this is automated or if @max-zilla approves by hand)
* `options(clowder_user = "you@example.com", clowder_pass = "yourPassword")`

Then the following ought to work.

```
gs_temp <- tempfile()
dir.create(gs_temp, showWarnings = FALSE, recursive = TRUE)

auth_info <- httr::authenticate(user = getOption("clowder_user"),
                                password = getOption("clowder_pass"))

json_result <- httr::with_config( #just for testing, to simplify authentication
  config = auth_info,
  download.geostreams(outfolder = gs_temp,
                      sitename = "UIUC Energy Farm - CEN",
                      start_date = "2016-07-01", end_date="2016-09-01"))

cf_result <- met2cf.geostreams(in.path = gs_temp,
                               in.prefix = json_result$dbfile.name,
                               start_date = json_result$startdate, end_date = json_result$enddate,
                               outfolder = gs_temp)
```

The resulting CF ought to work for any standard manipulation/validation; substitute your favorite...

```
ef_cf <- ncdf4::nc_open(cf_result$file)
met_table <- load.cfmet(ef_cf, lat = 40, lon = -88,
                        start.date = "2016-07-01", end.date = "2016-08-31")

ncdf4::nc_close(ef_cf)
unlink(gs_temp)
```

**Comment by tonygardella** [comment]
@infotroph Just checking in. Are you still testing?

**Comment by infotroph** [comment]
@tonygardella Yes. I expect this will be ready for review later this week -- I'll label it done when ready.

**Comment by dlebauer** [comment]
@infotroph is this ready to merge?

**Comment by infotroph** [comment]
@dlebauer on consideration I don't know how to test this without adding more slow network calls to the test stack. Yes, merge this and we can fix the edge cases later.

**Pull request merged**
