### PR TITLE
met2model.SIPNET and read.register logger messages

### PR DESCRIPTION
**Pull request by annethomas**
Added logger.info messages to models/SIPNET/R/met2model.SIPNET.R and downgraded an error message in modules/data.atmosphere/R/read.register.R to warning.

## Description
In met2model.SIPNET.R, ncvar_get checks for several variables in the met netcdf file that may not be there; these are wrapped in the try function. If not present, met2model calculates the values on the fly. However, the user only sees the error message generated by ncvar_get. I added logger.info messages that follow the nc_var errors to inform the user when these variables have been filled in.

Also, when regional met doesn't have a site id, such as CRUNCEP, there is a logger.error message in read.register saying the site id is undefined. Adding the site id causes other problems and isn't necessary for the met to download and the model to run. To lessen confusion, I downgraded the error to a warning.

## Motivation and Context
Both of these changes are relevant to the output of met.process for CRUNCEP and will make debugging a little clearer.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by annethomas** [comment]
I'm not sure what's going on with the 35 additional commits from earlier.

**Comment by annethomas** [comment]
@robkooper This branch is only 3 commits (my commits) ahead of develop but 38 ahead of release, and it looks like those commits are from others back in May. Do you know why this might be happening?

**Comment by annethomas** [comment]
@robkooper Oh, this appears to be from pull request #1468 which was recently merged. What can I do about this?

**Comment by robkooper** [comment]
@mdietze do you want that pull request to be in release as well?

**Comment by mdietze** [comment]
@robkooper Yes, I'd wanted Raiho to pull #1468 into the release as well, so while this is inadvertent it works out fine.

**Pull request merged**
