### PR TITLE
#717 EDR R wrapper

### PR DESCRIPTION
**Pull request by ashiklom**
Basically resolves issue #717 

I tested this against my ED run on the cluster and it seems to work pretty well. In a nutshell, the script reads in the paths to history and ED2IN files, copies and renames the history file (to 120000 instead of 000000 -- note that the copy and rename operations are optional), copies and modifies the ED2IN file (also optional -- if no path is provided, it defaults to the ED2IN in `output.path`, which is the same directory the script looks for the EDR executable), generates the input spectra files, runs EDR (capturing any execution errors), reads in the output files, and returns a vector of albedo values.

This basic version does NOT actually modify the history file -- I'll get to work on that this week (2/15-2/19) -- meaning that the only parameters that can be modified from within R are the PROSPECT parameters and the date and time of the run.

The major function is `EDR`, which takes leaf optics as input (in addition to paths, etc.). There is also a `EDR.prospect` wrapper function that takes PROSPECT parameters directly.

@araiho You're up to review this. @serbinsh @mdietze @Viskari You all will be interested in this as well.

### CODE REVIEW

**Comment by ashiklom** [comment]
I just realized that, because it's been a while since my last pull request, this branch also includes changes to PROSPECT inversion. Aside from a few bug fixes and aesthetic enhancements, there are two important changes: 

1. `invert.auto` function that automatically runs multiple chains and performs convergence checking.
2. Many arguments to `invert.custom` (and derivative functions) have been condensed into a list. This makes it much easier to load default inversion settings and modify them in place (just load the default list and modify it, rather than defining about a dozen individual variables in every inversion script).

**Comment by ashiklom** [comment]
Incorporated @araiho suggestions, and made a minor revision to the unit tests. With Ann's :+1: , I think this is ready to be merged.

**Comment by dlebauer** [comment]
This is awesome ... great work @ashiklom !

Are some of these functions sufficiently generic that they could be used in many different modules? If so, would it be worth moving them to 'utils' or 'uncertainty' package (I didn't do a full review, but noticed `check.convergence` and `invert.auto`, etc.

**Comment by ashiklom** [comment]
Thanks!

The invert custom and auto functions are designed to take any arbitrary
model, as long as the dimensions of its output align with the observation.
So there's no reason it couldn't be used with non spectral things.

@mdietze and I had discussed the possibility of having a PEcAn module for
just generalized inversion algorithms, but I think we agreed that we should
make sure not to reinvent the wheel and explore things that have already
been coded up by others.

**Pull request merged**
