### PR TITLE
New ED2IN for latest on GitHub

### PR DESCRIPTION
**Pull request by Aariq**
## Description

Taking a shot at updating the ED2IN file to reflect updates in the development version of ED2

## Motivation and Context

Docker container version of PEcAn.ED2 with development version of ED2 (https://hub.docker.com/r/pecan/model-ed2-git) doesn't work because the ED2IN file it contains is missing variables

**NOTE:** there's still one variable that I got an error for, `HYDAULIC_MORTALITY_SCHEME`, that doesn't exist in the most recent [ED2IN template](https://github.com/EDmodel/ED2/blob/master/ED/Template/Template/ED2IN)

## Review Time Estimate

- [x] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Aariq** [comment]
If you look at the diffs in the individual commits (rather than in the Files changed tab) it's easier to see the changes I made.

**Comment by dlebauer** [comment]
Should it be named ED2IN.r2.2.0.github? Or would it be worthwhile to create a new v2.2.1 in the ED2 repository?

**Comment by Aariq** [comment]
> Should it be named ED2IN.r2.2.0.github? Or would it be worthwhile to create a new v2.2.1 in the ED2 repository?

I think it would make sense to make an ED2 release now

**Comment by mdietze** [comment]
> > Should it be named ED2IN.r2.2.0.github? Or would it be worthwhile to create a new v2.2.1 in the ED2 repository?
> 
> I think it would make sense to make an ED2 release now

That's a decision that's up to the ED2 community. In terms of design, I don't think you can count on ED2 development versions having a distinct name.

**Comment by dlebauer** [comment]
> In terms of design, I don't think you can count on ED2 development versions having a distinct name.

I'll go ahead and merge, and also raise the suggestion on the ED2 slack.

**Review by dlebauer — COMMENTED** [review]
1. When you say 

> there's still one variable that I got an error for, HYDAULIC_MORTALITY_SCHEME,

Does that mean that this ED2IN doesn't work as-is?

**Comment by dlebauer** [comment]
Where are the values encoded as strings (`myslsoc`, `myslhydro`, `my*` etc ) set?

**Comment by Aariq** [comment]
Oh, I thought I got all those.  Let me double-check

**Comment by Aariq** [comment]
They aren't set anywhere, but it sounded like they're only needed when `SOIL_HYDRO_SCHEME=2` and it is set to 0 in this file. 
```
   ! These variables are used to define the additional soil properties needed for      !
   ! SOIL_HYDRO_SCHEME=2. 
```
 If you have ideas for defaults for these, I'd be happy to put some in.

**Comment by Aariq** [comment]
> When you say
> 
> > there's still one variable that I got an error for, HYDAULIC_MORTALITY_SCHEME,
> 
> Does that mean that this ED2IN doesn't work as-is?

No, I found it and added it. I had a typo on my search string.

**Review by dlebauer — APPROVED** [review]

**Pull request merged**
