### PR TITLE
Fix Typo Errors and Errors in Markdown documentations

### LINKED ISSUE #3245: Outdated Links in Documentations
### Document Change needed

Various links throughout `README` files have been shifted to a new address, do not exist or have been outdated due to lack of Updates over period of time. Some were last updated over 6 years back. I would like to correct this redundancy in Documents.

Example: 
+ The documentation link to external target in `documentation/README.md` gives 404 error.
+ Additional Resources in `CONTRIBUTING.md` such as the `href` to [Adding models to PEcAn](https://pecanproject.github.io/pecan-documentation/master/adding-an-ecosystem-model.html) is outdated.

### Information for those wanting to make changes

Please follow the instructions in the [documents](https://pecanproject.github.io/pecan-documentation/develop/about-the-pecan-book.html#bookediting) section of the documentation. 

All R-markdown files related to documentation are located within the main directory `/pecan/book_source` except for the demos and vignettes which are in `pecan/documentation/tutorials`.

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Improved the quality of `CONTRIBUTING.md` and other markdown files:
+ places where code block was left unidentified, for example `bash` blocks, were changed to bash code blocks. 
+ Linting and Alignment issues fixed in documentations.

I do not have permission to select labels and would like admins to add `enhancement` and `documentation` label to the PR

## Description

It does not actually fix #3245 because I do not have access to modified links, but I surely can change them if provided with the links.
## Motivation and Context

Fixes markdown linting issues in `CONTRIBUTING.md`

#3245 
## Review Time Estimate

- [ ] Immediately
- [x] Within one week
- [ ] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by RohanSasne** [comment]
Thanks for the PR @Sweetdevil144 ,if you're interested in contributing to the documentation further then maybe you can explore the issue : #2576 , we would appreciate your help :)

**Comment by Sweetdevil144** [comment]
@RohanSasne Sure !! I'll look more into it and create a PR for the same !!

**Comment by Sweetdevil144** [comment]
**Ready to be merged**
@RohanSasne I've made all possible documentation improvements. Just one question are documentations like `NEWS.md` and `CHANGELOG.md` auto generated? If yes, then we would need changes in configuration of auto generation file to remove some basic errors.

**Comment by mdietze** [comment]
NEWS and CHANGELOG are not autogenerated. It's always good to note changes in the latter as part of a PR

**Review by mdietze — APPROVED** [review]

**Pull request merged**
