### PR TITLE
Create ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by dlebauer**
I am proposing this template  for new issues in order to help users provide necessary information and improve consistency in reporting

### CODE REVIEW

**Comment by mdietze** [comment]
Not a bad idea, but I think the template itself needs work. This template seems set up for Issues that are requesting new features, but a large fraction of issues are bugs (which need different information, such as error messages and reproducible examples), while others are noting tools, models, and data sets we should be thinking about using/supporting. More generally, the tone seems a bit defensive, which could be off-putting

**Comment by serbinsh** [comment]
I have to agree with @mdietze on the tone/language.  The bug/request questions are a bit direct and it may be hard for new(er) users to identify how their request fits into the larger scope, even if it would be helpful more generally.  

I would suggest expanding to have the ability to report bugs, feature requests, or updates to existing features or options. For bugs, the context should request the parameters (of the workflow, not model params) of the run or analysis and even what step or function call, if possible. We should also be sure to request log or output errors to be attached.  

For new tools, data or models, that might be a bit easier and then I can see a simple request asking what the use would be or why it would be good to include for their analysis as well as others.

Of course none of this is hard just requires a bit of a re-org/expansion of this template.

**Comment by dlebauer** [comment]
Good points. I just copy pasted and simplified a generic template and didn't put enough thought into the audience.

I assigned Tony since he gave such a great talk on cultivating the PEcAn community this week.

**Comment by dlebauer** [comment]
ps I also put in a pull request template but forgot to push. It's on the way.

**Comment by serbinsh** [comment]
No worries @dlebauer my comments weren't criticisms and I realized it was just a quick seed for a larger discussion!

**Comment by tonygardella** [comment]
:+1:  I like this idea. When working one on one with people I always try to encourage them to create issues or talk to us in gitter but they often seem reluctant. I think with a general template to organize their ideas it would make it less cumbersome for them to communicate the key points to their problem.

**Comment by tonygardella** [comment]
I'll also be adding these to the gitbook.

**Pull request merged**
