### PR TITLE
Status.* overhaul

### PR DESCRIPTION
**Pull request by infotroph**
## Description

This is a refactoring of the utils::status.* functions that tries to address several longstanding issues:

* Removes reliance on a global settings object (#18, our oldest open issue!), but still allows it for backwards compatibility:
  - Old behavior: Take input/output path from `settings` if it exists, otherwise return without doing anything. 
  - New behavior: Accept a "file" argument so that users can directly specify which STATUS file to read/write. If `file` not provided, still look for a `settings` object and use it if it exists.
* Doesn't fail when settings$outdir doesn't exist.
  - Old behavior: Assume that `settings$outdir` exists and is writable, allowing `cat` to fail if it isn't. When this happened while `status.end` was being called inside the `workflow.R` error handler, this was sometimes making workflows fail to stop on SEVERE (e.g. #1428). 
  - New behavior: If `file` isn't specified, check whether `settings$outdir` exists and is writeable. If so, write to `<settings$outdir>/STATUS`. If not, write to the console as a last-ditch backup. 
  - NB I'm not sure I took the right direction here! See Context section.
* Combined documentation of all four functions into one Rd file, for easier overview of what they all do.
* Added tests.

## Motivation and Context

I started this while debugging an issue similar to #1428: My workflow continued after issuing a logger.severe and I tracked it back to a bad filepath causing an error in `status.end` inside the workflow's error handler, so I tried to make it impossible for bad paths to cause an outright failure. 

But now that I've implemented it, I'm not sure I took the right approach. Opening the PR for discussion, but expecting we'll need to iterate rather than merge this as it is. I think the following are all good arguments *against* my implementation:

* The point of these functions is to write to a status file, so it's appropriate for them to complain if they can't find/create a file. Writing to the console instead is kind of silly -- most modules will announce their start and end there anyway.
* If our long-term goal is to stop relying on a global settings object, is making it optional here a step in the right direction or just adding complexity? Maybe it's better to switch outright and require that all status calls specify the path to the status file.
* It's a worthy goal to make sure no errors happen inside an error handler, but maybe that concern should be handled in the error handler (e.g. wrapping status.end in a tryCatch) rather than changing the design of the status functions.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by infotroph** [comment]
(Whatever other changes this needs, it *definitely* needs a CHANGELOG entry too.)

**Comment by mdietze** [comment]
* I don't think we should retain backward compatibility on the existence of a global `settings` object. We need to fix those entirely, not halfway -- if a function wants to have a dependency on settings it has to passed in explicitly as an arg.
* Would it be better to write to the current working directory rather than the console if there's no file? I think if it's an error message the file is NULL then console is fine, but if you're in a place that really requires a file, then `getwd`.

**Comment by infotroph** [comment]
> We need to fix those [global settings] entirely, not halfway

Check. I'll strip out the settings lookup.

> Would it be better to write to the current working directory

@mdietze I like `getwd` as a unix-y default for many functions, here I'd lean towards having no default and complaining if no path is given -- I can't think of any other workflow functions that assume cwd, and I think refusing to have a default is probably helpful for avoiding local vs remote mixups.

**Comment by infotroph** [comment]
Since fully stripping out the global settings object requires an interface change (new mandatory `file` parameter), here's a possible alternate approach: 

1. Move these refactored status functions to the PEcAn.workflow package, since that's where they're used.
1. Leave existing utils::status* as they were before this PR, but mark them as deprecated and scheduled for removal in PEcAn 2.0.
1. While we're mucking with the interface: The current usage pattern uses a fair amount of boilerplate, and will use more with a mandatory file argument:
```
if (PEcAn.utils::status.check("MODEL", statusfile) == 0) {
  PEcAn.utils::status.start("MODEL", statusfile)
  PEcAn.remote::runModule.start.model.runs(settings, stop.on.error = FALSE)
  PEcAn.utils::status.end(statusfile)
}
```
Perhaps we can collapse this into a single wrapper that handles all the status lookups/writes for a modules, e.g. something like
```
with_status(statusfile, "MODEL", PEcAn.remote::runModule.start.model.runs(settings, stop.on.error = FALSE))
```

**Comment by robkooper** [comment]
One other option is to write this to the database, that way all systems have access to the status of each workflow, and on top we don't have to read it from disk to get the status. We can add now just do a single query and get all information about the workflow, including the status of each step. We can leverage of the attributes table for this.

**Comment by infotroph** [comment]
@robkooper this raises a design question: 

I've been assuming* the STATUS file was intended as a permanent artifact that would stay with the output for reference/diagnosis after the run (maybe including being zipped up, copied around, then inspected by a human reader without access to the DB). If so, keeping a static file seems useful.

 Is it actually more for use by the system to keep track of stages *during* workflow execution, with any archival uses secondary? If so, then moving it to the DB seems reasonable.

*Now that I think about it, I don't know why I assumed this... Maybe only because it seemed like there had to be a reason it didn't live in the DB already!

**Comment by mdietze** [comment]
I'd been working under a similar assumption to @infotroph.  Before we switch this to the DB, which would take more coding than the current fix focused on paths not existing,  I think we'd need a large discussion of the pros and cons. My concerns initial are

1. how will this complicate remote operations, which need to run without talking to the DB
2. this seems likely to lead to missed status logs when errors occur
3. do we really need to be syncing this info across machines

but on the plus, it would make it easier to query (and thus possibly clean up) failed runs.

**Comment by infotroph** [comment]
I've opened #2488 for discussion of a switch to DB; for this PR I will keep writing to files, but a `with_status` wrapper would  be easy to update later to include notifying other backends.

**Comment by mdietze** [comment]
I do like the `with_status` idea

**Comment by infotroph** [comment]
@mdietze I don't think this should have been merged yet -- my takeaway from the discussion above was that I needed to refactor first. Sorry for not marking WIP

**Comment by robkooper** [comment]
@infotroph I think we can do that in a new pull request based on #2488 .

**Pull request merged**
